### ISSUE TITLE
Unable to access suitecrm when mount volume /bitnami

### ISSUE THREAD

**Issue by acecombat2** [bitnami/bitnami-docker-suitecrm#101]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

I'm using openmediavault docker plugin to host bitnami suitecrm docker container. I mount the /bitnami volume to my own designated folder for persistence. However, I could not access the website. Bitnami SuiteCRM docker image version 7-debian-9
![bitnami suitecrm 1](https://user-images.githubusercontent.com/31785435/60749171-bb876900-9fc8-11e9-8a9f-a4d98c6e6d7d.PNG)

I tried without mount volume /bitnami it works alright.

**Steps to reproduce the issue:**

1. Install OpenMediaVault and docker plugin
2. Run Container of Bitnami SuiteCRM
3. Access web with designated dockerhost port.

**Describe the results you received:**

as per image in description and....

`[0m
[0m[1mWelcome to the Bitnami suitecrm container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-suitecrm[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-suitecrm/issues[0m
[0m
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing suitecrm
suitecr INFO  ==> Preparing webserver environment...
suitecr INFO  ==> Preparing PHP environment...
suitecr INFO  ==> suitecrm has being already initialized, restoring...
suitecr INFO  ==> Setting extra configuration...
suitecr INFO  ==> Configuring Cron Jobs...
suitecr INFO
suitecr INFO  ########################################################################
suitecr INFO   Installation parameters for suitecrm:
suitecr INFO     Persisted data and properties have been restored.
suitecr INFO     Any input specified will not take effect.
suitecr INFO   This installation requires no credentials.
suitecr INFO  ########################################################################
suitecr INFO
nami    INFO  suitecrm successfully initialized
[0m[38;5;2mINFO [0m ==> Starting suitecrm...
Starting Apache...
[Sat Jul 06 07:57:01.210809 2019] [so:warn] [pid 111] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.28.0.14. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 06 07:57:01.234958 2019] [ssl:warn] [pid 111] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 07:57:01.236172 2019] [ssl:warn] [pid 111] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 07:57:01.375754 2019] [so:warn] [pid 111] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.28.0.14. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 06 07:57:01.388952 2019] [ssl:warn] [pid 111] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 07:57:01.390163 2019] [ssl:warn] [pid 111] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 07:57:01.511417 2019] [mpm_prefork:notice] [pid 111] AH00163: Apache/2.4.39 (Unix) OpenSSL/1.1.0k PHP/7.1.30 configured -- resuming normal operations
[Sat Jul 06 07:57:01.515018 2019] [core:notice] [pid 111] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[Sat Jul 06 07:58:07.703852 2019] [core:error] [pid 115] [client 192.168.100.152:49986] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
192.168.100.152 - - [06/Jul/2019:07:58:07 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218
[Sat Jul 06 07:58:08.654236 2019] [core:error] [pid 115] [client 192.168.100.152:49986] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
192.168.100.152 - - [06/Jul/2019:07:58:08 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218
192.168.100.152 - - [06/Jul/2019:07:58:09 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218
[Sat Jul 06 07:58:09.280826 2019] [core:error] [pid 115] [client 192.168.100.152:49986] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
[Sat Jul 06 08:11:14.726919 2019] [core:error] [pid 116] [client 192.168.100.152:50006] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
192.168.100.152 - - [06/Jul/2019:08:11:14 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218
[Sat Jul 06 08:11:26.342928 2019] [mpm_prefork:notice] [pid 111] AH00169: caught SIGTERM, shutting down
[0m
[0m[1mWelcome to the Bitnami suitecrm container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-suitecrm[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-suitecrm/issues[0m
[0m
[0m[38;5;2mINFO [0m ==> Starting suitecrm...
Starting Apache...
[Sat Jul 06 08:11:51.442223 2019] [so:warn] [pid 50] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.28.0.14. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 06 08:11:51.466804 2019] [ssl:warn] [pid 50] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 08:11:51.468526 2019] [ssl:warn] [pid 50] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 08:11:51.616137 2019] [so:warn] [pid 50] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.28.0.14. Set the 'ServerName' directive globally to suppress this message
[Sat Jul 06 08:11:51.630305 2019] [ssl:warn] [pid 50] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 08:11:51.632702 2019] [ssl:warn] [pid 50] AH01909: 172.28.0.14:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 06 08:11:51.763787 2019] [mpm_prefork:notice] [pid 50] AH00163: Apache/2.4.39 (Unix) OpenSSL/1.1.0k PHP/7.1.30 configured -- resuming normal operations
[Sat Jul 06 08:11:51.763947 2019] [core:notice] [pid 50] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[Sat Jul 06 08:12:04.354192 2019] [core:error] [pid 54] [client 192.168.100.152:50010] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
192.168.100.152 - - [06/Jul/2019:08:12:04 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218
[Sat Jul 06 08:12:05.387063 2019] [core:error] [pid 54] [client 192.168.100.152:50010] AH00037: Symbolic link not allowed or link target not accessible: /opt/bitnami/suitecrm
192.168.100.152 - - [06/Jul/2019:08:12:05 +0800] "GET /index.php?action=Login&module=Users HTTP/1.1" 403 218`

**Describe the results you expected:**

Access the web without issues. I Expected able to upload documents with persistence data. Mount Volume. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Nothing  out of ordinary.

**Version**
HostOS
Linux kkg8server 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux
- Output of `docker version`:

```
Docker version 18.09.7, build 2d0083d
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Open Media Vault Docker Plugin

**Comment by acecombat2** [comment]
Ok..... after 6 hours tried to understand what could be the problem, I found out is the permission the folder created own by group (root) and user (user) rwxrw-r- where else the ownership in docker is group (daemon) and user (daemon) with permission rwxr-xr-x. So All I have to do is change the ownership of folder similar inside the docker.

**Comment by acecombat2** [comment]
Dittoca

**Comment by alemorcuq** [comment]
I'm glad you were able to troubleshoot your issue. Please, don't hesitate to open another ticket if you find any further problems.

**Comment by philippe78** [comment]
I have the same issue. What you did to fix it ? Did you re-own all the files to root or to Deamon ?

**Comment by acecombat2** [comment]
> I have the same issue. What you did to fix it ? Did you re-own all the files to root or to Deamon ?

I chown from root to daemon @ host to match within the docker image permission.
