### ISSUE TITLE
Can't get token for V8 API

### ISSUE THREAD

**Issue by leolird** [bitnami/bitnami-docker-suitecrm#106]
reproduce evn:
```
$ docker -v
Docker version 19.03.7, build 7141c199a2
$ docker-compose -v
docker-compose version 1.24.0, build 0aa59064
```
reproduce step:
1. download the docker-compose.yml from https://github.com/bitnami/bitnami-docker-suitecrm
2.  change the expose port of  suitecrm to
```
    ports:
      - '8000:80'
      - '442:443'
```
3. use the command `docker-compose up -d` to get the crm up
4. for now i can visit the website throw both http://localhost:8000/ and https://localhost:442/
5. excute `docker exec -it suitecrm_suitecrm_1 bash` to enter the crm container and execute the follow command:
```
cd bitnami/suitecrm
composer install
```
Go to Admin Panel → Repair → Rebuild .htaccess File

```
cd bitnami/suitecrm/Api/V8/OAuth2/
openssl genrsa -out private.key 2048
openssl rsa -in private.key -pubout -out public.key
sudo chmod 600 private.key public.key
sudo chown daemon:daemon p*.key
```

Update encryption key:

```
sudo apt update
apt install vim
openssl rand -base64 32
vi /bitnami/suitecrm/Api/Core/Config/ApiConfig.php
```
change the value of const OAUTH2_ENCRYPTION_KEY with the one just generated (use command `openssl rand -base64 32`)
 6. then i create a new Client Credentials Client with 
name=test 
Change secret=111111
after save i got a ID=6d068a46-f2b8-472b-6139-5e607ee3538f
7. go to postman
![image](https://user-images.githubusercontent.com/9332514/75947801-9858e480-5edc-11ea-92bc-cf07e568e15d.png)
get the error:
![image](https://user-images.githubusercontent.com/9332514/75947857-bc1c2a80-5edc-11ea-9877-6c6f9156989f.png)
i also try to change the Access Token URL to https://localhost:442/Api/access_token
but got the same error
then i  enter the container to check the apache error_log under /opt/bitnami/apache2/logs, it is show like blow:
`[Thu Mar 05 04:27:33.946013 2020] [php7:error] [pid 107] [client 172.23.0.1:33250] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Api\\Core\\Resolver\\ConfigResolver::{closure}() must be an instance of Interop\\Container\\ContainerInterface, instance of Slim\\Container given, called in /bitnami/suitecrm/vendor/pimple/pimple/src/Pimple/Container.php on line 118 and defined in /bitnami/suitecrm/Api/V8/Config/services/middlewares.php:20\nStack trace:\n#0 /bitnami/suitecrm/vendor/pimple/pimple/src/Pimple/Container.php(118): Api\\Core\\Resolver\\ConfigResolver::{closure}(Object(Slim\\Container))\n#1 /bitnami/suitecrm/vendor/slim/slim/Slim/Container.php(109): Pimple\\Container->offsetGet('League\\\\OAuth2\\\\S...')\n#2 /bitnami/suitecrm/Api/V8/Config/routes.php(17): Slim\\Container->get('League\\\\OAuth2\\\\S...')\n#3 /bitnami/suitecrm/vendor/slim/slim/Slim/RouteGroup.php(25): Api\\Core\\Loader\\RouteLoader->{closure}(Object(Slim\\App))\n#4 /bitnami/suitecrm/vendor/slim/slim/Slim/App.php(272): Slim\\RouteGroup->__invoke(Object(Slim\\App))\n#5 /bitnami/suitecrm/Api/V8/Config/routes.php(127): Slim\\App->group('', Object(Closure))\n#6 /bit in /bitnami/suitecrm/Api/V8/Config/services/middlewares.php on line 20`
can anyone tell me why this happen and why i can't get the token success ?
and is there any step i missed when configure the crm ?
thanks

**Comment by harrymaurya05** [comment]
I am facing the same issue. Have you found your solution ? if yes then can please share.

**Comment by rafariossaa** [comment]
Hi @harrymaurya05 ,
  Let's see if @leolird can help. 
  Did you follow the same steps ?

**Comment by harrymaurya05** [comment]
Yes .. after execute composer update its start  throwing  above error.

**Comment by rafariossaa** [comment]
It seems to be a error related to suiteCRM, we have had a similar issue [here](https://community.bitnami.com/t/authenticating-suite-v8-restapi-with-postman-404-error/88406/6) . 
Maybe it worth it to ask in suiteCRM forums.

**Comment by harrymaurya05** [comment]
@rafariossaa  @leolird 
have you found any solution for this?

**Comment by rafariossaa** [comment]
Hi,
  No, I don't have a solution for this.
  Did you ask in a suiteCRM forum ? Maybe they can bring in some ideas.

**Comment by harrymaurya05** [comment]
Yes, I asked it on Suitecrm forum but unfortunately, But I have not received any reply on it. 
A good thing that after a lot of research I found a solution. 
Since container-interop/container-interop is deprecated, simply replace it with Psr\Container\ContainerInterface a try. it works for me. 
I hope it will work for you as well.
@rafariossaa @leolird

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing I will take a look to that and see if something can be done in our side.

**Comment by harrymaurya05** [comment]
For as of now I just simply replace this 
**use container-interop/container-interop** 
to  **use Psr\Container\ContainerInterface**
in my all PHP file where we are using it.
But most probably I will modify my composer.json file later.
let me know if you need any help with it.
Thank you

**Comment by rafariossaa** [comment]
I am sorry, but unfortunately, as we package what suitecrm team releases, we are not be able to make a release with this issue fixed until they officially make a release with that replacement.

**Comment by leolird** [comment]
hi @rafariossaa & @harrymaurya05 , well i move on to docker-compose-lamp, it's a php running environment, base on that i modify some code to make it's support ssl, here is my fork https://github.com/leolird/docker-compose-lamp, then just deploy the suitecrm on that, works fine now, hope can help your guys

**Comment by rafariossaa** [comment]
Hi @leolird , 
  Thanks for letting us know.
  I am creating an internal task to take a look into it and check if we can do something in our image.
