### ISSUE TITLE
Changes on SUITECRM_USERNAME and/or SUITECRM_PASSWORD are not applied upon container re-creation

### ISSUE THREAD

**Issue by jlegido** [bitnami/bitnami-docker-suitecrm#109]
**Description**

If you re-create docker container and changed original SUITECRM_USERNAME and/or SUITECRM_PASSWORD those changes are not applied, keeping default values ('user' and 'bitnami').

**Steps to reproduce the issue:**

1. Get docker-compose file
```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml > docker-compose.yml
```
2. Bring up the containers
```
docker-compose up -d
```
3. Wait a bit until the product started up successfully
4. Login with default credentials: 'user' / 'bitnami'
https://yourhost
5. Edit file downloaded at step 1
```
vim docker-compose.yml
```
And replace by below content:
```version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=user2
      - SUITECRM_PASSWORD=bitnami2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```
6. Stop application container, keeping the database container alive
```
docker stop suitecrm_funny_container_name
```
7. Startup again the application container
```
docker-compose up suitecrm -d
```
8. Repeat step 4 but using below credentials:
* Username: user2
* Password: bitnami2

**Describe the results you received:**
Error:
```
You must specify a valid username and password.
```

**Describe the results you expected:**

Access to logged in page, since credentials are correct.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Docker version 19.03.8, build afacb8b7f0
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 74
  Running: 72
  Paused: 0
  Stopped: 2
 Images: 3355
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-4-amd64
 Operating System: Debian GNU/Linux bullseye/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.3GiB
 Name: my_server_name
 ID: *****
 Docker Root Dir: /a/valid/path
 Debug Mode: true
  File Descriptors: 539
  Goroutines: 437
  System Time: 2020-04-14T09:15:11.930286751+02:00
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
N/A
I would just wanted to add couple of things. First of all many thanks to all the people involved in this project for their time. Second use case that justifies the expected behaviour is automated provisioning with tools such as ansible.

I suggest below behaviour:

1. Check if username and/or password are the default ones
2. If no, no changes should be taken into consideration, completely ignore 'SUITECRM_USERNAME' and 'SUITECRM_PASSWORD', since we assume that the username already logged in and changed the credentials.
3. If yes check  'SUITECRM_USERNAME' and 'SUITECRM_PASSWORD' and update values accordingly if differ

**Comment by Mauraza** [comment]
Hi @jlegido,

The values are set when the container is created. When you stop and pick it up again, the variables do not change. If you wanna do this you have to recreate the container. 
The navigator has their 'cache' and the application have their login properties.

**Comment by jlegido** [comment]
Arratsalde on @Mauraza.

Not sure to understand you, but my point is even re-creating the container, thus changing the ENV values of the docker container, the username and password remains the same.

I assume (maybe I'm wrong) that is because:

* They are stored at database level (which is another container and in my use case I did NOT even stopped)
* The startup script running in application container does NOT changes the values at database level, which in my proposal should be expected.

Thanks.

**Comment by beltran-rubo** [comment]
Hi @jlegido, thanks for your feedback. It is very difficult to change all the settings via ENV vars every time you restart the container. The user credentials are stored in the database and there could be multiple scenarios e.g. you were able to create several admin users from the admin panel so the container does not know which one should we change. Those ENV vars are only valid for the first time you initialize the application.

**Comment by jlegido** [comment]
Hi @beltran-rubo.

Thanks for your quick reply. At this stage this issue can be closed, maybe I can create later on a feature request for future consideration and link to this ticket.
