### ISSUE TITLE
Is SuiteCrm Docker support postgresql?

### ISSUE THREAD

**Issue by asharabu** [bitnami/bitnami-docker-suitecrm#114]
Is SuiteCrm Docker support PostgreSQL?. If it's so please share the environment variables.

**Comment by javsalgar** [comment]
Hi,

At the moment our container only works with MySQL/MariaDB. However, I checked the official SuiteCRM installation guide and did not see any support for PostgreSQL. https://docs.suitecrm.com/admin/installation-guide/downloading-installing/

Did you try asking the SuiteCRM devs for this feature? I see a thread here https://community.suitecrm.com/t/support-for-postgresql-as-db-backend/11740
