### ISSUE TITLE
Replacing configuration paramers on startup after a backup restore

### ISSUE THREAD

**Issue by juanluisbaptiste** [bitnami/bitnami-docker-suitecrm#118]
**Description**

Hi,

We are migrating our suitecrm installs from an on-premises setup to aws. On the on-premises setup each service has its own db container and on aws we are using RDS, so on the new setup on aws the db connection information needs to be updated. 

We restore our backups on aws (copy suitecrm files to the designated volume location and loading the sql dump into RDS db) and then start the suitecrm container, the parameters we set wth the env variables with thew new db connection settings are not being replaced on the suitecrm config.php file, so the container continues to use the old values from the backup contents and have to be manually edited.

It seems the env variables are only used when setting a new install ?

**Steps to reproduce the issue:**

1. Restore a suitecrm install: (copy suitecrm files to the designated volume location and loading the sql dump into RDS db)
2. Configure on the docker-compose.yml or env_file file with the new values for MARIADB_HOST, SUITECRM_DATABASE_NAME, SUITECRM_DATABASE_USER and SUITECRM_DATABASE_PASSWORD and use the same suitecrm image version than the one of the backup.
3. Start suitecrm container.
4. Access the application from a web browser
5. See an error about nor being able to connect to the database.
6. Edit config.php and put the correct values
7. Access again the application and the login screen appears.

**Describe the results you received:**

It seems the values of the configured env variables are not being replaced on this use case.

**Describe the results you expected:**

Env variables values should always be replaced.

**Version**

Tested with suitecrm 7.11.15-debian-10-r97 and 7.11.6-debian-9-r4 (version used with the backup contents)

- Output of `docker version`:

```
sudo docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
sudo docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: y6mqb0xn0un94b0ddpj0h9rwc
  Is Manager: true
  ClusterID: 0cqk9brw700mfdwidyhy0cj8o
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789 
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1   
   Election Tick: 10   
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.250
  Manager Addresses:   
   10.0.0.250:2377
 Runtimes: runc
Default Runtime: runc 
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-11-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64  
 CPUs: 2
 Total Memory: 1.914GiB
 Name: ip-10-0-0-250   
 ID: 74T6:5AEW:RRM7:BEJL:4NBL:WZXA:7FTL:NPF4:YEXP:DBAZ:LOX3:DAYL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false   
 Insecure Registries:  
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker swarm cluster on AWS EC2.

**Comment by carrodher** [comment]
Thanks for reporting this issue, at this moment we are working on refactoring the SuiteCRM logic. I added this information to the refactoring task to be taken into account. We'll update this issue once a version using the new logic was released

**Comment by juanluisbaptiste** [comment]
Excellent, thanks :+1:

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
