### ISSUE TITLE
www.example.com:8443:0 server certificate does NOT include an ID which matches the server name

### ISSUE THREAD

**Issue by nimal** [bitnami/bitnami-docker-suitecrm#120]
Description
Not able to start container after update to 7.11.18

Steps to reproduce the issue:
Update suiteCRM container from 7.11.15 to 7.11.18

Describe the results you received:
After updating the docker I am not able to start the container (I am using UNRAID).
The following warning is seen in the log: "www.example.com:8443:0 server certificate does NOT include an ID which matches the server name" 

Is there an environment variable for the server name like the APACHE_HTTPS_PORT_NUMBER?

Version
latest suitecrm Version 7.11.18
UNRAID 6.8.3

**Comment by FraPazGal** [comment]
Hello @nimal,

The latest version of this container includes a major overhaul and backward compatibility is not guaranteed. What is the updating process you followed?

I would recommend exporting the content of your current container and importing them to the new SuiteCRM container. For more information about the introduced changes, please take a look at our [README](https://github.com/bitnami/bitnami-docker-suitecrm#71118-debian-10-r13).

**Comment by nimal** [comment]
Hi @FraPazGal ,-

Thank you so much for the quick reply.

In UNRAID there is an option to upgrade with just a button press. Unfortunately, I didn’t read the README before the update.

I tried to re-install the container with the port modifications. However, I think the issue is the server name, which I can’t set using an environment variable. I am using reverse proxy and letsencrypt so I cannot change the Apache settings. I tried to use the SUITECRM_HOST variable, but it doesn’t change the server name.

Do you have any suggestions to solve the issue?

**Comment by nimal** [comment]
Hi again,-

I just installed the 7.11.17 tag and it's working without any issues. However, I do see the same warning: **_"www.example.com:443:0 server certificate does NOT include an ID which matches the server name"_**
Since I am able to start the container and access it using reverse proxy the problem with 7.11.18 might be related to something else..

**Comment by FraPazGal** [comment]
Hello @nimal,

Happy to know your app is up and running! 

Regarding the warning, yes, it is expected to be present. This container uses apache, a component which is compiled internally with a basic autogenerated SSL for testing. You can find the apache ssl configuration at `/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf`.

**Comment by jokerigno** [comment]
Hi @nimal do you have a template to share for Unraid?

**Comment by nimal** [comment]
Hi @jokerigno,-

I have attached a screenshot of my settings. If you have any question just let me know. However, I don't think we should continue the conversation in this ticket. Since it's not related to this ticket.

![suitecrm_unraid](https://user-images.githubusercontent.com/8339517/111461197-3355e280-871d-11eb-9ded-e5ddd5ae1de6.png)
