### ISSUE TITLE
schedulers cronjobs not working

### ISSUE THREAD

**Issue by juanluisbaptiste** [bitnami/bitnami-docker-suitecrm#122]
**Description**

Cronjobs are not enabled, at least since 7.11.16. On the schedulers page on the Admin section it says that to enable them  there should be the following cron job under the daemon user:

` *    *    *    *    *     cd /bitnami/suitecrm; php -f cron.php > /dev/null 2>&1 `

But the crontab of that user is empty:
```
$  sudo crontab -l -u daemon
no crontab for daemon
```

**Steps to reproduce the issue:**

1. Connect to the suitecrm container
2. Run  sudo crontab -l -u daemon

**Describe the results you received:**

Crontab for user daemon is empty.

**Describe the results you expected:**

The crontab for user daemon should be configured with this job:

*    *    *    *    *     cd /bitnami/suitecrm; php -f cron.php > /dev/null 2>&1 

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 100
 Server Version: 20.10.1
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 203
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.58GiB
 Name: airbourne
 ID: TC3S:JPSS:UKUB:3O3B:YOXU:T52E:QHE5:52ST:4R3O:5V2O:5F4R:T3X7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Tested with installations on both AWS and on premises with swarm. I have this issue with installs on 7.11.16 and 7.11.18.

**Comment by miguelaeh** [comment]
Hi @juanluisbaptiste ,
As you can see in the file `libsuitecrm.sh` the corn jobs will be created only if the image is run as root the first time. So it is configured using the cronjobs:
```
162     # Ensure SuiteCRM cron jobs are created when running setup with a root user
163     cron_cmd=(cd "${SUITECRM_BASE_DIR};" "${PHP_BIN_DIR}/php" "-f" "cron.php")
164     if am_i_root; then
165         generate_cron_conf "suitecrm" "${cron_cmd[*]} > /dev/null 2>&1" --schedule "*/1 * * * *"
166     else
167         warn "Skipping cron configuration for SuiteCRM because of running as a non-root user"
168     fi
```

We moved this image to be non-root so from now on, by default they are not created.

**Comment by juanluisbaptiste** [comment]
Hi @miguelaeh so two questions:
1. How do I get them created or run the image as root ? this is an old install coming from 7.10.x when it runned as root and when updated at some point the cronjobs stopped working because of this.
2. What's the point of having a broken install by default were there are no cronjobs ?

**Comment by miguelaeh** [comment]
Hi @juanluisbaptiste ,
> How do I get them created or run the image as root ? this is an old install coming from 7.10.x when it runned as root and when updated at some point the cronjobs stopped working because of this.

About this, since they were breaking changes you should have followed the steps at https://github.com/bitnami/bitnami-docker-suitecrm#71118-debian-10-r13

> What's the point of having a broken install by default were there are no cronjobs ?

About this, the default installation is not broken, but the cron jobs cannot be configured as a non-root user, so in case you need to use them, you will need to run this image as root. SuiteCRM can work without cron jobs by default, they are an addition to the default behavior.

**Comment by juanluisbaptiste** [comment]
> About this, since they were breaking changes you should have followed the steps at https://github.com/bitnami/bitnami-docker-suitecrm#71118-debian-10-r13
> 

I did read it and I quote what it says:

> The SuiteCRM container now supports the "non-root" user approach, but _**it still runs as the root user by default**_. 

So it seems this changed at some point after r13 and wasn't documented, or can you point me where it says that the image now runs as non-root _by default_ ? 

Also I'm having this behavior with some 7.11.6-debian-r4 installations that I still have not updated:

```
root@e60d8e93bc05:/# env|grep BITNAMI_IMAGE_VERSION
BITNAMI_IMAGE_VERSION=7.11.6-debian-9-r4
root@e60d8e93bc05:/# crontab -l -u daemon
no crontab for daemon
root@e60d8e93bc05:/# crontab -l -u root
no crontab for root
root@e60d8e93bc05:/# id 
uid=0(root) gid=0(root) groups=0(root)
root@e60d8e93bc05:/# 
```

> About this, the default installation is not broken, but the cron jobs cannot be configured as a non-root user, so in case you need to use them, you will need to run this image as root. SuiteCRM can work without cron jobs by default, they are an addition to the default behavior.

Correct me if I'm wrong, but without the cronjobs some feature like these are missing:

- Mail inbox checking
- Scheduled campaigns sending
- Lucene and AOD indexing and optimizations
- Email notifications
- Database cleaning jobs like pruning of tables or cleaning of queues
- etc

So yes, SuiteCRM works but has some very important features missing if you are not running the cronjobs, that's what I meant with a broken, or better worded, a half working installation by default. IMO security is not of an enough justification to disable all this features _by default_ , without users knowing the features that are going to stop working. They should take this decision knowingly of the sacrifices they are going to make for the sake of better security.

As a suggestion, you could run a separate cron container to run the cronjobs alongside the suitecrm _non-root_ container and not sacrifice any of the functionalities.

**Comment by miguelaeh** [comment]
Hi @juanluisbaptiste ,
I am sorry for the confusion. This image still runs as root by default due to the cronjobs unless you specify it to be non-root.
You can't see the created cronjobs using `crontab` because we add them to `/etc/cron.d`. From a fresh deployment of the container using the docker-compose provided at the repo:
```
root@90892731dd37:/# ls -l /etc/cron.d/suitecrm
-rw-r--r-- 1 root root 97 Jan  7 09:36 /etc/cron.d/suitecrm
root@90892731dd37:/# cat /etc/cron.d/suitecrm
*/1 * * * * root cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php > /dev/null 2>&1
```

**Comment by juanluisbaptiste** [comment]
Hi @miguelaeh ,

> Hi @juanluisbaptiste ,
> I am sorry for the confusion. This image still runs as root by default due to the cronjobs unless you specify it to be non-root.
> You can't see the created cronjobs using `crontab` because we add them to `/etc/cron.d`. From a fresh deployment of the container using the docker-compose provided at the repo:

Thank you for the clarification, I can verify I have the cronjobs file on that location too, but still cronjobs are not working. The field "Last Successful Run" for all tasks say last run was more than a month ago. I ran the cronjob line manually and got a syntax error from php.ini file:

```
root@dab66a01006d:/# su daemon -s /bin/sh -c "cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php"
PHP:  syntax error, unexpected '=' in /opt/bitnami/php/lib/php.ini on line 3
```

And looking at the file contents indeed there is a syntax error:

```
root@dab66a01006d:/# head opt/bitnami/php/lib/php.ini -n 4
memory_limit = 256M
extension = imap.so
= 60M
post_max_size = 60M
root@dab66a01006d:/#

```
So at some point that file got broken. I can remove the "= 60M" that I suppose is the same `post_max_size = 60M` with the key missing, but the question is, why this happened and will the modification persist after a container restart ?

**Comment by juanluisbaptiste** [comment]
I just looked at a fresh `7.11.18-r1` install and `/opt/bitnami/php/lib/php.ini` seems to be different, it starts with the usual file comments, it looks like a default php.ini file and not like the file in my broken install that seem to have some variables inserted at the beginning of the file. Also `post_max_size = 8M` instead of 60M.

**Comment by juanluisbaptiste** [comment]
With another container also on 7.11.6 were the cronjobs are also not working, if I run them manually they work, but not in a scheduled way:

```
root@944effa4dc9b:/# cat /etc/cron.d/suitecrm 
* * * * * root su daemon -s /bin/sh -c "cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php > /dev/null 2>&1"

root@944effa4dc9b:/#
root@944effa4dc9b:/# su daemon -s /bin/sh -c "cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php"
PHP Warning:  include(custom/metadata/estme_estudio_mercado_estme_estudio_mercadoMetaData.php): failed to open stream: No such file or directory in /bitnami/suitecrm/custom/application/Ext/TableDictionary/tabledictionary.ext.php on line 16
PHP Warning:  include(): Failed opening 'custom/metadata/estme_estudio_mercado_estme_estudio_mercadoMetaData.php' for inclusion (include_path='/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/custom/application/Ext/TableDictionary/tabledictionary.ext.php on line 16
root@944effa4dc9b:/#
```
The only difference with the other one is that there are a couple of warnings about a custom module, but when that command is run manually it works so they should be be the issue that don;t let it run on cron schedule.

**Comment by miguelaeh** [comment]
Hi @juanluisbaptiste ,
We have been investigating this and the issue is a typo in the default cron configuration. IT was set to be run as the root while it should be a daemon. We are fixing it and a new image revision will be published with the correct cron.
Thank you very much for reporting it.

**Comment by juanluisbaptiste** [comment]
Excellent, thanks.

**Comment by antonius-pl** [comment]
Hey, thanks on your work exploring this problem. Is there any update regarding a new image?
I'm experiencing the same sort problem on the latest docker image (r72).

**Comment by miguelaeh** [comment]
Hi @antonius-pl ,
Thank you for remebering this. We experienced some internal issues in our pipeline and the changes were not released. I will force the release now.
Sorry for the inconvenince.

**Comment by antonius-pl** [comment]
@miguelaeh 
Amazing! Thanks it works just as expected rn!

**Comment by miguelaeh** [comment]
Thank you for the confirmation @antonius-pl !
