### ISSUE TITLE
The MARIADB_ROOT_PASSWORD environment variable is empty or not set

### ISSUE THREAD

**Issue by sutidor** [bitnami/bitnami-docker-suitecrm#123]
**Description**
When installing, I get the error `The MARIADB_ROOT_PASSWORD environment variable is empty or not set` although I set the env.

```
echo "install suitecrm"
docker run -d --name suitecrm \
        --net=sumnet \
        --restart unless-stopped \
        -e MARIADB_ROOT_PASSWORD="$MARIADB_PW" \
        [...]
        --volume suitecrm_data:/bitnami \
        bitnami/suitecrm:latest
```

**Steps to reproduce the issue:**

1. install mariadb
2. install suitecrm using above command
3. docker logs suitecrm show mentioned error
4. checking to connect to mariadb with password copied from docker inspect suitecrm env MARIADB_ROOT_PASSWORD works

**Describe the results you received:**

suitecrm container wont run and keeps restarting showing the above message

**Describe the results you expected:**

suitecrm fire up normally

**Version**

- Output of `docker version`:
```
[redacted]
```

- Output of `docker info`:

```
[redacted]
```

**Comment by miguelaeh** [comment]
Hi @sutidor ,
Be sure to export the `MARIADB_PW` before running the docker command.
Also, I recommend you to adapt the following docker-compose: https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/docker-compose.yml

**Comment by sutidor** [comment]
Hi @miguelaeh, thanks for your quick reply.
My further investigation shows that it works fine with 7.11.16 image, but not with the latest 7.11.18.

### Resolution
(R)RTFM aka. re-read the manual
The `MARIADB_ROOT_PASSWORD` in the images has been replaced by
`MYSQL_CLIENT_DATABASE_ROOT_PASSWORD` (+ many other complementary vars have been added too)
which is a very good thing. Unfortunately **the error message hasn't been replaced yet!** That was very misleading. Please consider updating it:
[Actual Error Message](https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/libmysqlclient.sh)
[Similar Error Message](https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/7/debian-10/rootfs/opt/bitnami/scripts/libsuitecrm.sh)

**Comment by miguelaeh** [comment]
Hi @sutidor ,
Thank you very much for sharing the solution.
About the suggested change, I have been trying to reproduce the error to see the wrong message, but the one I obtain is:
```
The SUITECRM_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.
```
Which is correct. Indeed, the MARIADB_ROOT_PASSWORD does not seem to be used for SuiteCRM.
Could you detail how to obtain that log? Are you using the last versions for the images?

**Comment by sutidor** [comment]
Hi @miguelaeh, this was the docker run, which failed:
```
docker run -d --name suite \
        --net=somenet \
        --restart unless-stopped \
        -e MARIADB_ROOT_PASSWORD='***F' \
        -e SUITECRM_DATABASE_USER=admin \
        -e SUITECRM_DATABASE_NAME=db \
        -e MYSQL_CLIENT_CREATE_DATABASE_USER=db_admin \
        -e MYSQL_CLIENT_CREATE_DATABASE_NAME=db \
        -e MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=***p \
        -e SUITECRM_DATABASE_PASSWORD=***p \
        -e ALLOW_EMPTY_PASSWORD=no \
        -e SUITECRM_USERNAME=admin \
        -e SUITECRM_PASSWORD=***r \
        -e SUITECRM_EMAIL=suite@domain.tld \
        -e SUITECRM_LAST_NAME=Name \
        -e SUITECRM_HOST=suite \
        -e SUITECRM_SMTP_HOST=smtp.domain.tld \
        -e SUITECRM_SMTP_PORT=465 \
        -e SUITECRM_SMTP_USER=funky@domain.tld \
        -e SUITECRM_SMTP_PASSWORD=*S \
        -e SUITECRM_SMTP_PROTOCOL=SSL \
        --volume suite_data:/bitnami \
        bitnami/suitecrm:latest
```

**Comment by miguelaeh** [comment]
Hi @sutidor ,
it is weird since the `MARIADB_ROOT_PASSWORD` does not seem to appear in the code of the suitecrm container.

**Comment by sutidor** [comment]
Interestingly, the same issue occured in the [Matomo](https://github.com/bitnami/bitnami-docker-matomo) container of bitnami's.
I set the `MARIADB_ROOT_PASSWORT` but did not set the `MYSQL_CLIENT_DATABASE_ROOT_PASSWORD` as the docs suggest. Same error. I knew from messing with the suitecrm container that I might wanna use the `MYSQL_CLIENT_DATABASE_ROOT_PASSWORD` var, which worked fine, though it isn't even mentioned in the docs.

**Comment by miguelaeh** [comment]
Hi @sutidor ,
Thank you for reporting it. It seems that there is an error in the Matomo docs. There should be a section similar to : (this one)[https://github.com/bitnami/bitnami-docker-suitecrm#create-a-database-for-suitecrm-using-mysql-client] that is missing.
