### ISSUE TITLE
Synology Docker

### ISSUE THREAD

**Issue by dazzaling69** [bitnami/bitnami-docker-suitecrm#126]
Not sure if this is a bug or not.  I have a working Bitnami SuiteCRM instance on a Synology NAS's Docker app with a SuiteCRM instance and associated MariaDB instance.  The one thing I don't seem to be able to do is to access the files in user-accessible space for persistence, i.e. the SuiteCRM and database files, and also, for similar reasons I can't back up the database.

I think this is a problem relating to the Volumes setting.  I'm sorry but this Docker does not do compose files, so I need to figure this out in the way the app needs it done.

I'm not sure what to map If I set the volumes as in the attached image.  I get the error below.  Can anyone help with the correct settings?

Start container bitnami-mariadb1 failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/opt/bitnami/scripts/mariadb/entrypoint.sh\\\": stat /opt/bitnami/scripts/mariadb/entrypoint.sh: no such file or directory\": unknown"}.

![image](https://user-images.githubusercontent.com/26164009/104302061-413e7b80-54c0-11eb-8877-c8871026011c.png)

**Comment by andresbono** [comment]
Hi @dazzaling69, if you take a look at the [docker-compose.yml](https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/7/debian-10/docker-compose.yml), you can see that only a volume is needed for each container:

```
...
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
...
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
...
```

You should specify those mount paths (`/bitnami/mariadb` and `/bitnami/suitecrm`) in your platform.

**Comment by dazzaling69** [comment]
Hi Andres, 

I added the volume links to an existing working SuiteCRM instance.  That did solve the problem of the docker failing immediately, and it allowed mariadb to start writing to the external folder with what looked like an empty database.  SuiteCRM, however, failed with various issues - log excerpt attached - and it wrote nothing to the external folder.  It also failed to serve any web pages.

I wonder if this is because I did it with an existing docker and I didn't move the files in those directories to the new location.  In which case, do I just need to move the contents of the relevant folders into the external ones and restart the docker instances?  Or would I need to reinstall a fresh docker and somehow import the data into SuiteCRM?

![image](https://user-images.githubusercontent.com/26164009/104446435-5be12500-5592-11eb-9c45-5607b893745d.png)

**Comment by dazzaling69** [comment]
I tried to find where the files are stored - I assumed in the hidden files Synology doesn't let regular users access - and couldn't find where docker stores the files for its containers.  

My problem is that I have data in an existing container, but it doesn't have the volumes mapped.  I can't see a way to add the mapping later or export the data to import it back into a new instance.

Any suggestions on how I can set my docker up with volume mapping and keep the data I already have in the SuiteCRM instance that I'm currently using?

**Comment by andresbono** [comment]
Hi @dazzaling69, you might find [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) useful for what you are trying to do.

You should copy and backup the whole `/bitnami/mariadb` directory from the existing mariadb container and `/bitnami/suitecrm` from the existing suitecrm container. Those directories are the mount points for the volumes.

I'm not familiar with Synology but you would need to replicate the volume mapping from this [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/7/debian-10/docker-compose.yml) in order to make it work properly with volumes.

**Comment by dazzaling69** [comment]
Thanks.  I can see how that would work, but it seems the Synology docker implementation is working against me!

**Comment by andresbono** [comment]
Let's see if other members of the community can help you with the specifics of Synology docker.

**Comment by dazzaling69** [comment]
Thanks Andres.  I was able to solve this only by either restarting the NAS or creating a new container manually (or both - I did both).  Then the mapping stuck and it all now works.  Phew!

One other issue I have now is coexistence.  I have two sets of mariadb and suitecrm containers running different CRMs.  Although their external port mappings are different they interfere with each other.  I can't see why, since the internal ports (443, 80, 3306) are mapped to different external ports.    If I access one CRM then the other logs me out, and vice versa.  I thought the whole point of Docker was strict container separation...

Do you have any idea how can they be interfering with each other and how can I stop it?

Darren.

**Comment by andresbono** [comment]
That's great news! :tada:

>  If I access one CRM then the other logs me out, and vice versa.

What do you mean by "logs me out"? Do you mean in the web interface? The 4 containers are running, right?

**Comment by dazzaling69** [comment]
I have all 4 containers running.  I can use each CRM individually fine, but if I have both CRMs running, use one and then start using the other, then the first one logs out.  They are somehow interacting with each other in a way that doesn't make sense to me.

**Comment by andresbono** [comment]
It is indeed very strange... What if you use two different web browsers or two different devices to access each site? Does the problem occur?

**Comment by dazzaling69** [comment]
Hi Andres,

I have managed to get this Docker to pretty much do what I want, but one last thing is backups from SuiteCRM.  I can backup using the SuiteCRM admin process, and I can specify the output folder as upload.  It completes successfully, but I can't access the file.

I can't find another folder with write permission, e.g., /bitnami/suitecrm doesn't work.

Trying to map the folder /upload to a system folder in Docker doesn't work (although, thinking about it now, perhaps I should have tried /bitnami/upload).

Do you know how I can backup to a folder I can access and link to my system's user-accessible filesystem?

Darren.

**Comment by miguelaeh** [comment]
Hi @dazzaling69 ,
You should be able to do what you are trying by mounting a directory.
>I can't find another folder with write permission, e.g., /bitnami/suitecrm doesn't work.

About the perimssion issue, since `suitecrm` uses the user `1001`, if you mount a local volume you should first change the permissions of it in your local machine to user `1001`.
I hope this helps
