### ISSUE TITLE
Version / Feature Policy

### ISSUE THREAD

**Issue by christf** [bitnami/bitnami-docker-suitecrm#131]
As discussed in https://github.com/bitnami/bitnami-docker-suitecrm/issues/105
the docker-compose file is meant to run with older versions of suitecrm.

This means that never in the future can a feature be added that relies on external infrastructure - like elasticsearch in the case of #105.

Allowing for people using older versions by cjust changing the version tag is a great feature. At the same time this limits the scope of this project.

I propose to consider a change of the current policy and introduce a mechanism (maybe with release branches / maintenance branches) that clarifies which docker-compose file works with which suitecrm versions.
This would allow including new features in the future while retaining the desirable property for easy version changes for users.

**Comment by carrodher** [comment]
Hi, thanks for your suggestion.

The _docker-compose.yaml_ is tested before being pushed to GitHub, those tests include verification and functional tests to ensure the published _docker-compose.yaml_ works as expected with the container image tag that contains at this moment.
By using the git history in the repo you can go back to any previous version of the _docker-compose.yaml_ that is expected to work with the container image bundled. Modifying the container image or customizing the _docker-compose.yaml_ is something that, although should work (depending on the customization), it's not tested on our internal test & release pipeline so we cannot guarantee that it will work as it should

**Comment by christf** [comment]
Thank you for your message. I am not sure how to connect it to my initial proposal though.

in #105 it was discussed that elasticsearch cannot be added to the docker-compose file because that would break older installations. Now you are rightly pointing out that it is possible to go back toprevious versions of the compose file using git although that is untested (of course). Which versions of suiteCRM are tested against the newest version of the compose file?

My proposal addresses the policy mentioned in #105 and I argue it should be possible to add elasticsearch while achieving the goal of compatibility by taking into account versioning.

**Comment by carrodher** [comment]
> Which versions of suiteCRM are tested against the newest version of the compose file?

The docker-compose.yaml uses a rolling that, `7` at this moment:
```yaml
  suitecrm:
    image: docker.io/bitnami/suitecrm:7
```

This rolling tag is pointing to the latest image we release every day, see https://github.com/bitnami/bitnami-docker-suitecrm#supported-tags-and-respective-dockerfile-links, at this moment it is pointing to `7.11.19`. Those are the versions that are tested before each release (including docker-compose and helm chart).
+info: https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/
