### ISSUE TITLE
History not saving

### ISSUE THREAD

**Issue by dazzaling69** [bitnami/bitnami-docker-suitecrm#132]
I am using Bitnami SuiteCRM 7-debian-10 and Mariadb 10.3 debian 10.  It was working fine for a while but then SuiteCRM stopped saving creating Notes or Attachments.

If I go to History for any record, then select Create Note or Attachment I can complete the note, but it doesn't save after I hit the Save button.

How can I fix this?

**Comment by rafariossaa** [comment]
Hi,
  Did you check the logs from suiteCRM and mariadb ?

**Comment by dazzaling69** [comment]
Testing it further it seems that the history is stored against only some of the linked items. I had linked it against the contact, but expected it to link to the opportunity and the account and the contact, but it doesn't do that.

So it seems not a bug but a feature.

Darren.

**Comment by dazzaling69** [comment]
I was incorrect in my earlier assumption that it worked.  It seems to not save most times but will save to, e.g., a Contact (in the Related To field) when saving to an Account.

This is very reproducible, but nothing seems to show up in logs.

Darren.

**Comment by rafariossaa** [comment]
Hi,
 Could you indicate the image tag you are using ? I would like to try to reproduce it.

**Comment by dazzaling69** [comment]
Mariadb:10.3-debian-10
Suitecrm:7-debian-10

Is it possible to easily upgrade the Docker instances?

**Comment by rafariossaa** [comment]
Hi,
  I could reproduce the issue, however it seems not related to the docker image but to suiteCRM UI.
  I would suggest you to open a ticket in suiteCRM's forums, and see if it something known and has a workaround or fix.

**Comment by dazzaling69** [comment]
Thanks.  If the fix is an update of the installation what is the best way to do that?  Is it to upgrade in place or install a later image then move the files over?  Which is the latest recommended image?

**Comment by rafariossaa** [comment]
I can not tell in advance. 
It would depend on how they fix it. If it is a new release, a new release of the container would be made by us. If it is some kind of workaround I would need first to take a look on how it need to be applied.

**Comment by dazzaling69** [comment]
Is there a later container I could try the database on to see if it fixes the problem?  I suspect that the SuiteCRM forum might be slow to respond, if at all.

**Comment by rafariossaa** [comment]
Right now, uur latest image is 7.11.19, you can check it [here](https://github.com/bitnami/bitnami-docker-suitecrm/#user-content-supported-tags-and-respective-dockerfile-links).
