### ISSUE TITLE
SuiteCRM 8

### ISSUE THREAD

**Issue by siddjellali** [bitnami/bitnami-docker-suitecrm#138]
#Request 

Hi team, 
Could you please map SuiteCRM 8 ?
Thanks.

**Comment by siddjellali** [comment]
Appreciate your return.
Any change to add this RC ? As you should know @salesagility doesn't provide dockerfile :/

**Comment by pablogalegoc** [comment]
AFAIK we've never shipped a non-stable package, sorry

**Comment by siddjellali** [comment]
Appreciate your feedback 
Thanks

**Comment by siddjellali** [comment]
you're late ^^ #joke <3

**Comment by RHV044** [comment]
Hello Everyone! 
Any updates on supporting v8?
Thanks!

**Comment by carrodher** [comment]
Our system already detected the new version, since it is a major version there are some manual changes required on our internal test & release pipeline. At this moment the team is working on it, I can't provide an ETA but it's being handled at this moment.
