### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by christf** [bitnami/bitnami-docker-suitecrm#142]
The suitecrm 7.12.0 image was created on 2021-10-29, then updated on 2021-10-30, updated again on 2021-10-31 and yet again on 2021-11-08 all with the very same tag.

This approach breaks reproducible deployments.

**Describe the results you expected:**

docker image pull bitnami/suitecrm:7.12.0 always fetches the very same image with the same shasum.

**Comment by yilmi** [comment]
Hi @christf,

Immutable tags are the ones specifying a revision number, you could achieve what you want using for example tag [7.12.0-debian-10-r10](https://github.com/bitnami/bitnami-docker-suitecrm/releases/tag/7.12.0-debian-10-r10). Which also links to a github tag pointing to the state used to build the image.

More details are available in this blog post: https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/

Let me know if that covers your ask 👍
