### ISSUE TITLE
Version 7.12 seems to be 7.11.19

### ISSUE THREAD

**Issue by ThomasDonath** [bitnami/bitnami-docker-suitecrm#147]
### Name and Version

bitnami/suitecrm:7.12.5-debian-10-r27

### What steps will reproduce the bug?

1. Deploy it with Bitnamis Helm chart
2. open the Web-UI and look into Admin/About

### What is the expected behavior?

see a SuiteCRM version 7.12.x

### What do you see instead?

7.11.19

**Comment by carrodher** [comment]
Unfortunately, I'm not able to reproduce the issue. Using the same image (`bitnami/suitecrm:7.12.5-debian-10-r27`) the version displayed on the About page is the expected one (7.12.5):

![Screenshot 2022-03-31 at 16 39 40](https://user-images.githubusercontent.com/13216600/161081883-ed5af173-8094-4c17-bc12-95bd5526805e.png)

Not sure if you are persisting some files from previous deployments that can be causing the issue you're describing.

**Comment by ThomasDonath** [comment]
thank you very much. I'm persisting applications files - so I'm going to check there... Thank you very much
