### ISSUE TITLE
Suitecrm8 container with PHP8.0

### ISSUE THREAD

**Issue by sweettbug3** [bitnami/bitnami-docker-suitecrm#148]
### Name and Version

bitnami/bitnami-docker-suitecrm

### What is the problem this feature will solve?

Suitecrm8 container is still using PHP7.4 which is no longer actively supported by PHP (only security support).  It would be nice to push forward to the newer PHP8.0.

### What is the feature you are proposing to solve the problem?

Will require pulling in the appropriate PHP8.0 version, and compose files might require changes.

### What alternatives have you considered?

Modifying the docker container myself, but I believe the community would rather move forward.

**Comment by carrodher** [comment]
Thanks for letting us know. In fact, we have an ongoing task related to this topic. Although PHP 7.4 is supported until November, we are moving our PHP applications to, at least, PHP 8.0 when it is possible. 

Being said that, there are some cases where the upstream application itself doesn't support PHP 8.X, in those cases we can't do anything until the application itself is updated by the app developers.

I will move this Issue to on-hold and update it once the PHP version is bumped for SuiteCRM

**Comment by sweettbug3** [comment]
Suitecrm 8 does claim to support php 8.0, php 7.4, and php 7.3.  So there is no technical reason to hold off, but thanks for the response. 


https://docs.suitecrm.com/8.x/admin/compatibility-matrix/ <https://docs.suitecrm.com/8.x/admin/compatibility-matrix/>

**Comment by dgomezleon** [comment]
Hi @sweettbug3 ,

We have released both SuiteCRM 7 and 8 with PHP 8.0.
