### ISSUE TITLE
Startup error legacy/config.php not found since 7.12

### ISSUE THREAD

**Issue by fstorz** [bitnami/bitnami-docker-suitecrm#151]
### Name and Version

bitnami/suitecrm:7

### What steps will reproduce the bug?

Environment
1. MySQL Database container connected via dedicated docker network
2. Environment Variables for MySQL (Host, Port, DB-Name, User, Password) & ALLOW_EMPTY_PASSWORD=yes
3. Install SuiteCRM in version < 7.12 with persistent data (Volumes: `/opt/crm/data:/bitnami`& `/opt/crm/logs:/var/log/suitecrm`)
4. Update docker image to 7.12 -> see below error

### What is the expected behavior?

Normal startup of SuiteCRM

Logs from version 7.11.22
```
suitecrm 06:55:36.30 
suitecrm 06:55:36.30 Welcome to the Bitnami suitecrm container
suitecrm 06:55:36.30 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm 06:55:36.31 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm 06:55:36.31 
suitecrm 06:55:36.31 INFO  ==> ** Starting SuiteCRM setup **
suitecrm 06:55:36.38 INFO  ==> Configuring PHP options
suitecrm 06:55:36.39 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
suitecrm 06:55:36.42 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
suitecrm 06:55:36.46 INFO  ==> Restoring persisted SuiteCRM installation
suitecrm 06:55:38.09 INFO  ==> Trying to connect to the database server
suitecrm 06:55:38.25 INFO  ==> ** SuiteCRM setup finished! **

suitecrm 06:55:38.26 INFO  ==> ** Starting cron **
suitecrm 06:55:38.27 INFO  ==> ** Starting Apache **
```

### What do you see instead?

Logs from version >7.12
```
suitecrm 06:50:24.64 Welcome to the Bitnami suitecrm container
suitecrm 06:50:24.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm 06:50:24.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm 06:50:24.65 
suitecrm 06:50:24.65 INFO  ==> ** Starting SuiteCRM setup **
realpath: /bitnami/apache/conf: No such file or directory
suitecrm 06:50:24.68 INFO  ==> Configuring Apache ServerTokens directive
suitecrm 06:50:24.73 INFO  ==> Configuring PHP options
suitecrm 06:50:24.73 INFO  ==> Setting PHP expose_php option
suitecrm 06:50:24.75 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
suitecrm 06:50:24.84 INFO  ==> Restoring persisted SuiteCRM installation
suitecrm 06:50:24.84 INFO  ==> Trying to connect to the database server
PHP Warning:  require(/opt/bitnami/suitecrm/public/legacy/config.php): Failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  Uncaught Error: Failed opening required '/opt/bitnami/suitecrm/public/legacy/config.php' (include_path='.:/opt/bitnami/php/lib/php') in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami! Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
