### ISSUE TITLE
Unable to backup application state as per docker-compose instructions

### ISSUE THREAD

**Issue by komali2** [bitnami/bitnami-docker-suitecrm#153]
### Name and Version

bitnami/suitecrm:8

### What steps will reproduce the bug?

1. Ubuntu 18.04.6, after successfully following instructions to create a docker-compose deployment of bitnami/suitecrm, stop using `docker-compose stop suitecrm`. 
2. Attempt to run the backup command. On my server that looks like:

```
docker run --rm -v /src/suitecrm/backups:/backups --volumes-from suitecrm_suitecrm_1 busybox \ cp -a /bitnami/suitecrm /backups/latest
```

3. Observe the following error: 

```
 docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: " cp": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 


```

### What is the expected behavior?

I suppose I expected the backup command to run without error. 

### What do you see instead?

```
 docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: " cp": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
