### ISSUE TITLE
File '/opt/bitnami/php/conf/php.ini' does not exists

### ISSUE THREAD

**Issue by sguilly** [bitnami/bitnami-docker-suitecrm#30]
I have this error with the default docker-compose file

suitecrm_1  | suitecr INFO  Preparing webserver environment...
suitecrm_1  | suitecr INFO  Preparing PHP environment...
suitecrm_1  | Error executing 'postInstallation': File '/opt/bitnami/php/conf/php.ini' does not exists

**Comment by sameersbn** [comment]
@sguilly Can you please try with the release `bitnami/suitecrm:7.7.9-r2` and let us know if it resolves the issue?

**Comment by sguilly** [comment]
bitnami/suitecrm:7.7.9-r2 solve the issue.

Thanks for your work!
