### ISSUE TITLE
SuiteCRM installation fails on Ubuntu 16.04.2 x64

### ISSUE THREAD

**Issue by azlyth** [bitnami/bitnami-docker-suitecrm#44]
##### Description
I'm able to run the project just fine with `docker-compose` on Docker for Mac, but not on Docker on Ubuntu 16.04.2 x64.

##### Steps to reproduce the issue:
1. Have Docker on Ubuntu 16.04.2 x64
2. Clone `https://github.com/bitnami/bitnami-docker-suitecrm` and `cd` into it
2. Run `docker-compose up`

##### Describe the results you received:
A few different failures:

- On the initial run, `nami` is unable to find the pid file and the mariadb container quits
```
mariadb_1   | nami    INFO  mariadb successfully initialized
mariadb_1   | INFO  ==> Starting mariadb...
mariadb_1   | nami    ERROR Unable to start com.bitnami.mariadb: Cannot find pid file '/opt/bitnami/mariadb/tmp/mysqld.pid'.
```

- After a restart while keeping the volumes, SuiteCRM installation fails, so the suitecrm container quits
```
suitecrm_1  | suitecr INFO  Installing suitecrm. It could take some minutes...
suitecrm_1  | /opt/bitnami/base/helpers: line 13:    55 Killed                  nami ${NAMI_DEBUG:+--log-level ${NAMI_LOG_LEVEL:-trace}} initialize ${module} $inputs "${@:2}"
```

##### Describe the results you expected:
The SuiteCRM installation should complete

##### Additional information you deem important (e.g. issue happens only occasionally):
The networking seems to be a bit weird because on the initial `docker-compose up` call, port 3306 is closed on the `mariadb` container. After a restart, the `suitecrm` can reach the `mariadb` container fine, but fails to install. None of this is seen when running this on the Docker for Mac server.

###### Output of `docker version`:
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

###### Output of `docker info`:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4 MiB
Name: test-docker-droplet
ID: JLZ6:CLWI:GZ2C:MPFH:ILMD:W24W:WWNQ:AARV:INVX:KOFG:FARX:V35W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

###### Output of `docker-compose version` (if applicable):
```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

##### Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):

I've tried with both the Linux and Mac Docker clients. I've also tried running the images manually without docker-compose, but same failure.

The Ubuntu server is a Digital Ocean droplet created by `docker-machine`.

**Comment by sameersbn** [comment]
@azlyth We are investigating this issue and will get back to you soon.

**Comment by sameersbn** [comment]
@azlyth the issue is the default droplet has insufficient ram (512mb) to launch the `mariadb` and `suitecrm` containers in the same droplet.  If you take a look at the contents of `/opt/bitnami/mysql/logs/mysqld.log` you should find a line that reads `[ERROR] mysqld: Out of memory (Needed 128663552 bytes)`

Please specify `--digitalocean-size 1gb` to the `docker-machine create` command to provision a droplet with 1Gb RAM (10 USD/month) and retry the deployment with `docker-compose`.

Let us know if this resolves the issue.

**Comment by sameersbn** [comment]
also thanks for taking the time to write a very detailed issue report :heart:

**Comment by azlyth** [comment]
Using the 1GB droplet fixed the issue. Thanks for the really quick resolution. :)
