### ISSUE TITLE
upload directory & config.php

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#46]
Description:
--> suitecrm config.php is not correctly updated to point to the auto-generated randomPrefix upload directory

The link to the auto-generated semi-random upload directory is not changed in the config.php
-- specifically lines 92&93 in /root/.nami/components/com.bitnami.suitecrm/main.js do not have effect.

file permissions in suitecrm_data directory:
rw-rw-r--   1 daemon daemon   866 Mar  7 21:00 config_override.php
-rw-rw-r--   1 daemon daemon 10031 Mar  8 13:38 config.php
(config.php can be edited and changeed from within the docker instance as needed).

Environment: 
Docker version 17.03.0-ce, build 60ccb22
docker-compose version 1.11.1, build 7c5d5e4
Ubuntu 16.04 -- Linux 4.4.0-65-generic #86-Ubuntu SMP Thu Feb 23 17:49:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Binami image version: 7.8.1-r2
Docker Info:
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 72
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-65-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: 
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by dbarranco** [comment]
Hi @sergtech 

We have detected that issue and we're working to solve it, we will make soon a revision of the suitecrm container.
Meanwhile, you can change the name of the `RANDOM_NUMBER-upload` to the number you have in the config.php and you will avoid any error loading the images in suitecrm.

Also, could you explain what do you refer with this?

> file permissions in suitecrm_data directory:
rw-rw-r-- 1 daemon daemon 866 Mar 7 21:00 config_override.php
-rw-rw-r-- 1 daemon daemon 10031 Mar 8 13:38 config.php
(config.php can be edited and changeed from within the docker instance as needed).

I don't see here clearly the issue.

Thank you so much for reporting that. 
Best regards!

**Comment by sergtech** [comment]
Hi, David.


I have simply attempted to show you the file permissions for the files, 
in case it could have been related to inability to write to the file.


You can ignore it.

**Comment by sergtech** [comment]
Is there an update to a fix for this issue?
It's kind of a show stopper as it requires changing the config.php every time the container is restarted to have a working installation.

**Comment by dbarranco** [comment]
Hi @sergtech 

Currently we are testing that changes so we will release a revision of the module soon. 
I will update this thread to notify you.

Regards!

**Comment by dbarranco** [comment]
Hi @sergtech 

Just checked this in the recent changes made in the code and this problem is not reproducible anymore. We will notify you when we release this, just wanted to give you a quickly update.
Best regards

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform you that we've just released a revision of the module adding a few fixes.
I've checked this issue too and it seems it has been resolved.

Could you please give a try?
Looking forward to hear your feedback

Just executing:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml
$ docker-compose up
```

Should be enough to get the latest version.

Best regards!

**Comment by dbarranco** [comment]
I'm leaving open all your issues @sergtech 

Feel free to close them if you think they're resolved. 
Thanks

**Comment by sergtech** [comment]
Can't reproduce the issue anymore, but feels like the behavior has changed such that a random upload directory is no longer attempted each boot, and there's some sort of symlink to the 'upload' directory instead. Still works as intended and doesnt require editing of config.php every container restart  :-> :+1:
