### ISSUE TITLE
CRONjobs for suitecrm

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#47]
The docker container cannot run cronjobs, as the /etc/crontab is not persistent. These are required as part of the smoother system running for suitecrm.

I suggest adding something like
RUN echo "* *    * * *   root cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php 2>&1" >>/etc/crontab
to the dockerfile, or init scripts.

**Comment by dgonzalezruiz** [comment]
Hi! 

Could you please provide any reasons why you feel that this change is required? What is the motivation behind having cron jobs for SuiteCRM?

**Comment by dgonzalezruiz** [comment]
Hi!

We already configure cron jobs to work alright with SuiteCRM. Why do you want to have stateful cron jobs? They are recreated in every container initialization.

**Comment by sergtech** [comment]
I am not sure what you mean by they are working alright.

The docker container does not run the suitecrm cronjobs. A simple test is to go check the scheduled tasks within a deployed crm instance and you will find none of the tasks have been run - ever. 

for example the /etc/crontab of a newly deployed instance is "empty" (see at end). 

They are required to run for various housekeeping tasks, incoming e-mails, re-indexing of database for search...

root@8cb39ce0082c:/# cat /etc/crontab                                                                                                        
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
root@8cb39ce0082c:/# ls -la /etc/cron.hourly/
total 12
drwxr-xr-x  2 root root 4096 Feb 21 11:27 .
drwxr-xr-x 52 root root 4096 Mar  8 12:27 ..
-rw-r--r--  1 root root  102 Jun 11  2015 .placeholder

**Comment by joseajp** [comment]
Hello,

We checked the container configuration and we have identified the issue. We create the crontab correctly but we introduced a bug in a recent revision that prevented the crontab file to be loaded correctly. We are already working on the fix. Thanks!

**Comment by douglas-gibbons** [comment]
I can confirm it works with a Dockerfile like this:

`FROM bitnami/suitecrm:7-development`
`RUN echo "* * * * * root cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php 2>&1" >>/etc/crontab`

**Comment by carrodher** [comment]
Hi!
It seems that the issue has been solved [here](https://github.com/bitnami/minideb-extras/issues/114), if the problem persists using any version after 7.8.3-r0, please do not hesitate to reopen the issue.

Best regards

**Comment by sergtech** [comment]
The issue of having the crontab working may have been resolved, but SuiteCRM instances I run with 7.8.3-r0 and r1 do not have scheduled tasks running. 
In order to fix that I suggested an edit to the Dockerfile same as @douglas-gibbons mentioned above.

**Comment by javsalgar** [comment]
Hi, 

I just checked the Scheduled tasks in SuiteCRM and saw a list of active jobs. Are you still running into issues?

**Comment by sergtech** [comment]
@javsalgar My scheduled tasks are still not running. Here's my docker-compose.yml:

> version: '2'
> services:
>   mariadb_temptestCRM:
>     image: 'bitnami/mariadb:latest'
>     volumes:
>       - '/dev/shm/temptest/mariadb_data:/bitnami/mariadb'
>     environment:
>       - MARIADB_ROOT_PASSWORD=somepassword
>       - "TZ=Australia/Melbourne"
>   suitecrm_temptescrm:
>     image: 'bitnami/suitecrm:7.8.3-r2'
>     ports:
>       - '22222:443'
>     volumes:
>       - '/dev/shm/temptest/suitecrm_data:/bitnami/suitecrm'
>       - '/dev/shm/temptest/apache_data:/bitnami/apache'
>       - '/dev/shm/temptest/php_data:/bitnami/php'
>     environment:
>       - SUITECRM_USERNAME=user
>       - SUITECRM_PASSWORD=password
>       - SUITECRM_EMAIL=someone@test.net
>       - SUITECRM_LASTNAME=TempTestCRM
>       - SUITECRM_HOST=10.0.0.127:22222
>       - MARIADB_HOST=mariadb_temptestCRM
>       - MARIADB_PASSWORD=somepassword
>       - "TZ=Australia/Melbourne"
> 
>     depends_on:
>       - mariadb_temptestCRM

start container using
> docker-compose up

Go To Admin->Scheduler
Select Process WorkFlowTasks
Click on JobLog

Expected: List of most recent tasks run (every 1 minute by default)
Actual: empty list.

===Here's my container crontab: 

> # /etc/crontab: system-wide crontab
> # Unlike any other crontab you don't have to run the `crontab'
> # command to install the new version when you edit this file
> # and files in /etc/cron.d. These files also have username fields,
> # that none of the other crontabs do.
> 
> SHELL=/bin/sh
> PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
> 
> # m h dom mon dow user	command
> 17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
> 25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
> 47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
> 52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
> #

Note: running 
root@e3b20f74b74d:/# cat /opt/bitnami/suitecrm/conf/cron >>/etc/crontab 
still does not make the scheduler run properly as of 7.3.1-r2 (and it did properly in r0). This is despite the crontab now actually having the correct entry

Note 2: config.php contains:

> array (
>     'max_cron_jobs' => 10,
>     'max_cron_runtime' => 30,
>     'min_cron_interval' => 30,
>     'allowed_cron_users' =>
>     array (
>       0 => 'daemon',
>     ),

Note 3:
running
`su daemon -s /bin/sh -c "cd /opt/bitnami/suitecrm; /opt/bitnami/php/bin/php -f cron.php > /dev/null 2>&1"`
does successfully run through the scheduled tasks (once)

Note 4: 

> docker pull bitnami/suitecrm:7.8.1-r2
> 7.8.1-r2: Pulling from bitnami/suitecrm
> 1102976483fe: Already exists 
> ee3f1c14745a: Already exists 
> ea2cdf3f82e5: Already exists 
> 6f66735c51c5: Already exists 
> bceb2716ed2f: Already exists 
> a3ed95caeb02: Already exists 
> 21d320d326b2: Already exists 
> ebbfd4cd3279: Already exists 
> de1d23089d4a: Already exists 
> 0a54ca95680b: Already exists 
> 69bd87e87de5: Already exists 
> 92188af4dccd: Already exists 
> df60285b3c27: Already exists 
> Digest: sha256:47c3345fec998804bbb4b964167f8d4d590a5f6fd49c3712818fdb0163bb6663
> Status: Image is up to date for bitnami/suitecrm:7.8.1-r2

**Comment by carrodher** [comment]
Hi,

I am trying to reproduce your issue using `bitnami/suitecrm:7.8.1-r2` but for me cron jobs work well.
![screen shot 2017-05-24 at 17 30 54](https://cloud.githubusercontent.com/assets/13216600/26411757/f7d90612-40a6-11e7-9157-2bacb6d4cc5e.png)

Anyway, we just released a new SuiteCRM version, please, can you try it? You only need to replace 
```yaml
...
 suitecrm_temptescrm:
    image: 'bitnami/suitecrm:7.8.3-r2'
...
```
by 
```yaml
...
 suitecrm_temptescrm:
    image: 'bitnami/suitecrm:latest'
...
```

**Comment by sergtech** [comment]
@carrodher The list is of tasks you show are those that should be run, not of tasks that are running (or have completed). To see what has run, you click on the one called "Process Workflow Tasks" and then Go to "Job Log". My times stay empty, unless I modify the crontab in the 
![image](https://cloud.githubusercontent.com/assets/26265971/26438338/c108cca2-4165-11e7-8a9d-b0e66bd9595c.png)

**Comment by dbarranco** [comment]
Hi @sergtech , @carrodher 
Don't worry about this, I plan to create the PR fixing the cronjobs, this is something that has to be fixed in the initialisation scripts, not in the application code. 

I will update this when this is fixed, thanks guys

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform you that we've just released a new revision adding the fix for the cronjobs.
I've just tested manually and they're working as expected.

Could you please give a try? Just pull the latest image of the repo to get this working.


Best regards!!

**Comment by sergtech** [comment]
:+1: Looks good so far in r4. I'll do some more tests within the next 24 hours and then close this if everything is OK.

**Comment by sergtech** [comment]
Works for both brand new containers and for existing containers through the use of /etc/cron.d/suitecrm. Fantastic!
