### ISSUE TITLE
tcpdf issue

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#48]
Issue: Images that are part of PDF templates are not inserted in the output PDF file.

How to replicate issue:
1. Deploy container
2. Create a PDF template 
2.1 Load a sample PDF template (I tried the Invoice)
2.2 Save the template
3. Create an Invoice
4. Create a PDF using the new template

The output PDF will have a [x] where the image should be.

Environment:
Ubuntu 16.04 
[Docker version 17.03.0-ce, build 3a232c8]  [docker-compose version 1.11.1, build 7c5d5e4]

Note 1:
Issue does not exist in the bitnami installer package
Note 2: 
Issue exists with images inserted as both http(s) links and relative paths
Note 3: I could not find any error messages in the suitecrm log (with errorlevel=debug) or apache logs

**Comment by sergtech** [comment]
UPDATE: 
using a jpg file instead of the PNG works. 
Could be related to this bug:
https://github.com/salesagility/SuiteCRM/issues/2153
 
Could be a library issue in the docker image, as same version of suitecrm in bitnami application installer works fine with PNGs.

**Comment by joseajp** [comment]
We were able to reproduce the issue. The error is the following one:

```
mPDF error: IMAGE Error (themes/default/images/company_logo.png): Error parsing temporary file image object created with GD library to parse PNG image
```

To obtain that trace just apply this patch to the `modules/AOS_PDF_Templates/generatePdf.php` file:

```diff
diff --git a/modules/AOS_PDF_Templates/generatePdf.php b/modules/AOS_PDF_Templates/generatePdf.php
index ff1c770..e8d3958 100755
--- a/modules/AOS_PDF_TemplatesgeneratePdf.php
+++ b/modules/AOS_PDF_TemplatesgeneratePdf.php
@@ -141,6 +141,7 @@ if ($task == 'pdf' || $task == 'emailpdf') {
     ob_clean();
     try {
         $pdf = new mPDF('en', 'A4', '', 'DejaVuSansCondensed', $template->margin_left, $template->margin_right, $template->margin_top, $template->margin_bottom, $template->margin_header, $template->margin_footer);
+        $pdf->showImageErrors = true;
         $pdf->SetAutoFont();
         $pdf->SetHTMLHeader($header);
         $pdf->SetHTMLFooter($footer);
```

We will continue investigating the issue and trying to find a fix.

**Comment by sameersbn** [comment]
@sergtech could you please test this issue with the latest release if the image?

**Comment by sergtech** [comment]
Set my Demo system to run using 
image: 'bitnami/suitecrm:7.8.3-r1'
which i believe is the latest.
Issue still present.

Tried to set up a new blank system using the same image with same results. This occurred even with the default logo unchanged. Are you getting different results, or have a specific image you want me to try?

Note: On another suitecrm install that is not using bitnami, after upgrading to php7, the same issue presented itself. I still think this is a missing library or package for the default php7 compared to php5.

**Comment by dbarranco** [comment]
Hello @sergtech 

As reported in the [suiteCRM issues](https://github.com/salesagility/SuiteCRM/issues/2153) the problem could be related to the GD library of php, which is the one related to the generation of the images in the pdf's.

After checking the container it seems the php GD library is disabled by default, could you please try to enable it and try to reproduce the error?

To enable the GD library, you must do this:

* Go to `/opt/bitnami/php/conf` 

* Open the `php.ini` file with your favourite text editor
 
* Look for this line:

    `;extension=php_gd2.dll`

    * Delete the `;` character, the result should be:
    
    `extension=php_gd2.dll`

* After adding the module, you can restart apache with this command:
    `nami restart apache`

**Comment by sergtech** [comment]
Isn't the gd2_dll windows specific ? 
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/php_gd2.dll' - /opt/bitnami/php/lib/php/extensions/php_gd2.dll: cannot open shared object file: No such file or directory in Unknown on line 0 

also the package php7.0-gd not available in jessie repositories (`apt-get update && apt-cache search gd`). However! phpinfo() reveals: PHP Version 7.0.17 with GD enabled GD Version 	bundled (2.1.0 compatible) 

also php.ini could have been accessed from the host in CONTAINER/php_data/conf/php.ini

I can provide a copy of phpinfo() if that would help.

**Comment by sergtech** [comment]
Found the source of the problem: png image transparency; If the png file has an alpha channel, then the pdf output fails. 
Tested issue exists (and can be solved by removing alpha channel) in both bitnami/suitecrm:7.8.3-r1 and bitnami/suitecrm:7.8.3-r0. Probably the issue comes from the built-in gd library shipping with php 7.0. Should put this through to upstream package maintainers?

[Invoice_1-13.pdf](https://github.com/bitnami/bitnami-docker-suitecrm/files/969312/Invoice_1-13.pdf)

**Comment by javsalgar** [comment]
Hi, 

Indeed, we compile PHP with the bundled `gd`. Therefore, this definitely looks like an issue in their bundled component. I think it would make sense to report the `php` maintainers about this issue. Thanks for reporting.
