### ISSUE TITLE
config.php & config_override.php

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#50]
Admin -> System Settings 
does not save changes to the CRM.

Issue 1: Majority of settings in that page are not saved in either config or config_override.php
The file access permissions are set appropriately in the host O/S, and the file is writeable from within the docker container (for example "echo Hello >>config.php" works), however the settings are not persistent

File permissions in container:
daemon@c7216ae3e006:/opt/bitnami/suitecrm$ ls -la |grep config
lrwxrwxrwx  1 root root     28 Mar 19 09:27 config.php -> /bitnami/suitecrm/config.php
lrwxrwxrwx  1 root root     37 Mar 19 09:27 config_override.php -> /bitnami/suitecrm/config_override.php
File permissions outside container:
@M7510 ~/Docker/CRMDemo/suitecrm_data $ ls -la |grep config
-rw-rw-rw-   1 daemon daemon  1030 Mar 19 20:53 config_override.php
-rw-rw-rw-   1 daemon daemon 10038 Mar 19 20:39 config.php

Default file permissions on new install:
-rw-rw-r--   1 daemon daemon   629 Mar 19 21:13 config_override.php
-rw-r--r--   1 daemon daemon 10022 Mar 19 21:10 config.php
After config save, file permissions are:
-rw-rw-r--   1 daemon daemon   629 Mar 19 21:16 config_override.php
-rw-r--r--   1 daemon daemon 10022 Mar 19 21:10 config.php

Issue 2: The log file is not being created in the default "." directory (i.e.: 'log_dir' => '.' does not create a log file, while 'log_dir' => '/dev/shm/' does)

===================All but one of the apache processes are owned by user daemon in the container:
root        65  0.0  0.2 390644 46172 ?        Ss   09:26   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
root        91  0.0  0.3 960596 55524 ?        Sl   09:27   0:01 /opt/bitnami/nami/runtime/node --max_semi_space_size=150 /opt/bitnami/nami/index.js start --foreground apache
daemon      93  0.0  0.2 398064 42048 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      94  0.0  0.2 393256 32660 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      96  0.0  0.2 395444 37176 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      98  0.0  0.3 398080 48944 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     100  0.0  0.2 398124 44432 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     125  0.0  0.2 400064 43460 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     126  0.0  0.2 398020 42280 ?        S    09:27   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     152  0.0  0.2 393256 33216 ?        S    09:30   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     289  0.0  0.2 393252 32552 ?        S    09:52   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf

**Comment by joseajp** [comment]
Hello,

Thanks for your feedback. We have identified the issue. Since SuiteCRM is based on SugarCRM we created the `sugarcrm.log` file as the log file of the application. But, as you pointed, on the `config.php` file, `suitecrm.log` should be the correct log file of the application. Since the webserver user has not write permissions on the installation dir, it can create that file. 

Additionally, we are also working on fixing the inability of changing some configuration parameters using the System Setting panel. 

We will release soon a new revision fixing these issue.

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform you that we've just released a revision of the module adding a few fixes.
I've checked that the generation of the random string and the persistence of that folder and didn't find any errors.

Could you please give a try?
Looking forward to hear your feedback

Just executing:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml
$ docker-compose up
```

Should be enough to get the latest version.


Best regards!
