### ISSUE TITLE
Persistent Log

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#51]
Can the suitecrm log be made persistent?

**Comment by joseajp** [comment]
Hello @sergtech, while fixing #50 we are going to study if persisting the log directory could fit in our current approach.

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform that in the next revision of the module we're adding the suitecrm.log as another persisted file. 
Best regards.

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform you that we've just released a revision of the module adding a few fixes.
We also added the `suitecrm.log` (we fixed the name from `sugarcrm.log` to `suitecrm.log`) as a persisted file.

Just executing:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml
$ docker-compose up
```

Should be enough to get the latest version.

Looking forward to hear your feedback
Best regards!

**Comment by sergtech** [comment]
yay! persistent log is there! will keep testing and close this within 24 hours.
