### ISSUE TITLE
7.8.3-r2 Drop-down edit (Quotes,Invoices, others?)

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#57]
Issue: Editing an item (Quote) that has a drop-down field does not work when drop-down status changes.
1. Create a Quote
2. Re-open the quote to edit
3. Change the Drop-down "Approval Status" from 'Not Approved' to 'Approved'
4. Save Quote

Result: Blank Page
Expected Result: Return to Quote
New issue in 7.8.3-r1&r2. Works OK in r0.

Edit: Further tests show the Invoice is not affected, but only the Quote in r2.
Edit2: apache error_log:

> [Mon May 15 11:01:29.978741 2017] [:error] [pid 66] [client 10.0.0.81:34936] PHP Warning:  Declaration of SugarFieldMultienum::displayFromFunc($displayType, $parentFieldArray, $vardef, $displayParams, $tabindex) should be compatible with SugarFieldEnum::displayFromFunc($displayType, $parentFieldArray, $vardef, $displayParams, $tabindex = 0) in /bitnami/suitecrm/include/SugarFields/Fields/Multienum/SugarFieldMultienum.php on line 42, referer: https://10.0.0.196:22222/index.php
> [Mon May 15 11:01:29.991803 2017] [:error] [pid 66] [client 10.0.0.81:34936] PHP Warning:  require(metadata/audit_templateMetaData.php): failed to open stream: No such file or directory in /bitnami/suitecrm/include/database/DBManager.php on line 2798, referer: https://10.0.0.196:22222/index.php
> [Mon May 15 11:01:29.991886 2017] [:error] [pid 66] [client 10.0.0.81:34936] PHP Fatal error:  require(): Failed opening required 'metadata/audit_templateMetaData.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php:modules/AOD_Index/Lib') in /bitnami/suitecrm/include/database/DBManager.php on line 2798, referer: https://10.0.0.196:22222/index.php

**Comment by dbarranco** [comment]
Hi @sergtech 

Thanks for reporting it. I've been working on this and with the last changes I haven't been able to reproduce it. Will release a new revision of the module soon.

Thanks for your kind cooperation.

**Comment by sergtech** [comment]
Looking forward to it :+1:

**Comment by dbarranco** [comment]
Hi @sergtech 

Just wanted to inform you that we've just released a revision of the module adding a few fixes.
I've followed the steps you posted above and I haven't been able to reproduce them.

Could you give a try? Thank you so much.

Just executing:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml
$ docker-compose up
```

Should be enough to get the latest version.

Looking forward to hear your feedback
Best regards!

**Comment by sergtech** [comment]
Tested against r3. Looks Good so far. I'm closing this within 24 hours after some more testing.

**Comment by sergtech** [comment]
Tested against r4, for both new and existing systems. Problems is fixed.
