### ISSUE TITLE
Email Signature

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#59]
The e-mail signature creation pop-up window is blank on all instances of suitecrm:7.8.3-r4'.
To get to them, 
Go to 'All', then 'Emails', then 'Settings', then select 'Create' (regarding signature).
The pop-up window stays blank instead of loading the html editor for the signatures. 

Apache error_log
[Fri May 26 11:55:09.897051 2017] [:error] [pid 63] [client 172.22.0.1:36832] PHP Warning:  require_once(XTemplate/xtpl.php): failed to open stream: No such file or directory in /bitnami/suitecrm/include/utils/autoloader.php on line 67, referer: https://localhost:22222/index.php?module=Emails&action=index&parentTab=All
[Fri May 26 11:55:09.897082 2017] [:error] [pid 63] [client 172.22.0.1:36832] PHP Fatal error:  require_once(): Failed opening required 'XTemplate/xtpl.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/include/utils/autoloader.php on line 67, referer: https://localhost:22222/index.php?module=Emails&action=index&parentTab=All

root@9986d3fb108f:/# find |grep xtpl
./opt/bitnami/suitecrm/XTemplate/xtpl.php

Problem was introduced with suitecrm:7.8.3-r1 (r0 works correctly).

**Comment by andresbono** [comment]
Hi @sergtech,

Thanks for all the details. We have been able to reproduce the issue. We will investigate it and we will update this issue as soon as we have more information.

Best regards,
Andrés Bono

**Comment by dbarranco** [comment]
Hi @sergtech 

As I just answered in #60, it seems the error is related to `XTemplate`. Could you check if with the workaround posted in #60 is this also solved? 

We will release a revision of the module asap including by default that fix.
Thank you for your cooperation!

**Comment by sergtech** [comment]
Yep. All fixed now.
