### ISSUE TITLE
View Change Log not working 7.8.3-r4 and 7.9.0-r1

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#60]
Within the CRM, the "View Change Log" function does not appear to work (the blank pop-up remains 
blank).

1. Create a new Account (or PDF Template, or other).
2. After Save, Go to Actions and select View Change Log.
3. The pop-up window stays blank, instead of showing the change log.

This happens in "Accounts", "PDF Templates" and other modules.

Based on apache log below, appears related to Issue #59  I raised last week.

Apache log: 
[Fri Jun 02 13:19:41.248607 2017] [:error] [pid 7632] [client xx.xx.xx.xx:54852] PHP Warning:  require_once(XTemplate/xtpl.php): failed to open stream: No such file or directory in /bitnami/suitecrm/include/utils/autoloader.php on line 67, referer: https://yy.yy.yy.yy:12443/index.php
[Fri Jun 02 13:19:41.248704 2017] [:error] [pid 7632] [client xx.xx.xx.xx:54852] PHP Fatal error:  require_once(): Failed opening required 'XTemplate/xtpl.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/include/utils/autoloader.php on line 67, referer: https://yy.yy.yy.yy:12443/index.php

Edit: Added repeatability steps.

**Comment by dbarranco** [comment]
Hi @sergtech 

I've been able to reproduce the issue. These issues you're having are caused because the path in which suiteCRM is looking for his dependencies is `/bitnami/suitecrm/whatever`, so the workaroud here is to perform the execute commands:

`cp -rf XTemplate/ /bitnami/suitecrm`

and

`ln -s /bitnami/suitecrm/XTemplate/ XTemplate`

After that, I'm able to see the changelog. I'm sorry about these inconveniences.

**Comment by sergtech** [comment]
As per @dbarranco comment, 
`ln -s /opt/bitnami/suitecrm/XTemplate/ /bitnami/suitecrm/XTemplate`
solves the problem

**Comment by dbarranco** [comment]
Hi @sergtech 

Thanks for commenting. I will trigger the release process this afternoon.

Best regards.

**Comment by dbarranco** [comment]
Hi @sergtech 

We've just released the r2, could you confirm this issue have been solved?

Thank you.

**Comment by sergtech** [comment]
Looks good, all working! :+1:

**Comment by dbarranco** [comment]
Happy to read that!

Best regards @sergtech !! :)
