### ISSUE TITLE
Lots of "undefined" fields

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#64]
I am finding a lot of undefined fields in the latest version of the CRM (bitnami/suitecrm:7.9.4-r0).
For instance, in the Invoices modules, when creating a new invoice, when adding line items, all fields are undefined (see attached).
This only happens when the 
SUITECRM_HOST=https://fqdn.com:12345
is set in the docker-compose.yml file
It seems to work OK when 
SUITECRM_HOST=127.0.0.1:12345
only is set.

Maybe the way in which the parameter for SUITECRM_HOST is carried into the config.php should be adjusted to allow for https usage.
![undefined](https://user-images.githubusercontent.com/26265971/29152294-02c187ce-7dca-11e7-947c-95c0ee93ac10.png)

P.S.: I would appreciate a 'fix' to the 'undefined' problem without the need to re-create the container

**Comment by javsalgar** [comment]
Thanks for reporting. Have you tried setting the SUITECRM_HOST without the `https://`, otherwise the wizard will use `http://https://fqdn`. That doesn't mean you cannot access using https as Apache has SSL enabled.
