### ISSUE TITLE
Ability to configure database name

### ISSUE THREAD

**Issue by staegi** [bitnami/bitnami-docker-suitecrm#66]
It should be possible to set a database name by setting an env variable like MARIADB_NAME or something like that.

**Comment by juan131** [comment]
Hello @staegi 

At this moment, it's possible when using the MariaDB Docker Image but it's not possible when using SuiteCRM. By default, a new database will be created with the name "bitnami_suitecrm" for SuiteCRM app data.

Why do you need this parameter to be configured via env variable in particular?

**Comment by mattronix** [comment]
Because if you want to run multiple instances (testing, Development) or use a naming convention conform to an enterprise environment that has been pre configured it works better to allow database name to be specified.

**Comment by juan131** [comment]
I guess that a solution similar to the one implemented on WordPress Image to use existing database is what you're looking for. Please take a look to:

https://github.com/bitnami/bitnami-docker-wordpress#use-an-existing-database

We have an internal task to extend this to other Docker Images. I'd add this image to the list.

**Comment by RobinEd** [comment]
Has this been added to the list?
Also, when I create a local database bitnami_suitecrm running on centos and then try to acces it using docker-compose and the following docker-compose.yml

version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_USER=suiteuser
      - MARIADB_PASSWORD=test
      - MARIADB_HOST=192.168.0.30
      - MARIADB_PORT=3306
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier

the database does not populate. See also https://github.com/bitnami/bitnami-docker-suitecrm/issues/72 for the reason why I don't want to use the mariadb/bitnami database image. There are also no errors when docker-compose goes up.

The database is accessible from every host with that user.

**Comment by dbarranco** [comment]
Hi @RobinEd 

You're facing that error because the user `suitetest` won't have permissions in the database to write, as the database is created with a random prefix each time the container is started.. If you want to see a more verbose trace with the error, you can add the environment variable `NAMI_LOG_LEVEL=trace, and you will see this:

```
suitecrm_1  | mysql-c INFO  Trying to connect to MySQL server
suitecrm_1  | mysql-c INFO  Found MySQL server listening at 172.17.0.2:3306
suitecrm_1  | mysql-c TRACE [canConnect] Testing connection with 'suiteuser' user
suitecrm_1  | mysql-c TRACE [showDatabases] Getting databases for 'suiteuser' user
suitecrm_1  | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -h172.17.0.2 -usuiteuser -ptest -e SHOW DATABASES;
suitecrm_1  | mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_suitecrm\ninformation_schema\n","stderr":""}
suitecrm_1  | mysql-c TRACE [showDatabases] Databases: bitnami_suitecrm
suitecrm_1  | information_schema
suitecrm_1  |
suitecrm_1  | mysql-c TRACE [canConnect] Connection with 'suiteuser' user is successful
suitecrm_1  | mysql-c INFO  MySQL server listening and working at 172.17.0.2:3306
suitecrm_1  | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -h172.17.0.2 -usuiteuser -ptest -e SHOW DATABASES;
suitecrm_1  | mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_suitecrm\ninformation_schema\n","stderr":""}
suitecrm_1  | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -h172.17.0.2 -usuiteuser -ptest -e CREATE DATABASE IF NOT EXISTS `bitnami_suitecrm_adWZH`
suitecrm_1  | mysql-c TRACE [execute] Result: {"code":1,"stdout":"","stderr":"ERROR 1044 (42000) at line 1: Access denied for user 'suiteuser'@'%' to database 'bitnami_suitecrm_adWZH'\n"}
suitecrm_1  | Error executing 'postInstallation': MySQL command failed to run. Error:
suitecrm_1  |  ERROR 1044 (42000) at line 1: Access denied for user 'suiteuser'@'%' to database 'bitnami_suitecrm_adWZH'
suitecrm_1  |
suitecrm_1  | nami    TRACE Error: Error executing 'postInstallation': MySQL command failed to run. Error:
suitecrm_1  |  ERROR 1044 (42000) at line 1: Access denied for user 'suiteuser'@'%' to database 'bitnami_suitecrm_adWZH'
```

This will be solved once we add in the nami module the chance to add a custom database name, as you will be able to create a single user for this with fixed privileges.

In the meantime you can use an admin user with privileges to access to the database. (Take into account that you **must** set a secure password for this user) and change this when we release a new revision of the container including these changes. 

All you will have to do is create the new user with fixed privileges, the database and modify accordingly the environment variables in the docker-compose.


Best regards.

**Comment by RobinEd** [comment]
Thanks, it will be helpful to be able to name the database (and database user / pw) as an option in docker-compose.yml

I found that if you create the database bitnami_suitecrm before running docker-compose up for the first time, it creates the database name with random extension (bitnami_suitecrm_random). So make sure there is no suitecrm_bitnami database before you run docker-compose up.

**Comment by juan131** [comment]
We added this option recently to other docker images such as Magento, Mediawiki, Phpbb, Ghost and Drupal as we had done for WordPress.

We will continue adding it to this and other pending images. Thanks in advance for your consideration and patience. We will notify you about our progress.

**Comment by coolersport** [comment]
It seems that this has been implemented in the latest image. The supported environment variable is: SUITECRM_DATABASE_NAME

**Comment by juan131** [comment]
As you mentioned, this Docker Image supports now using an existing database. See https://github.com/bitnami/bitnami-docker-suitecrm#configuration for more details.

**Comment by mattronix** [comment]
Thanks!!
