### ISSUE TITLE
Add an option to populate sample/demo data  

### ISSUE THREAD

**Issue by Stephan-Berlin** [bitnami/bitnami-docker-suitecrm#70]
**Description**

I really like the docker image you provide here but at the moment there isn't a way to add demo-Data to SuiteCRM which is a key-feature for me. 

I wrote in the Bitnami [community support forum](https://community.bitnami.com/t/how-to-setup-demo-sample-data-with-the-docker-image/53417) and was asked to add an issue here aswell. 

**Steps to reproduce the issue:**

1. Install as decribed here: [bitnami-docker-suitecrm](https://github.com/bitnami/bitnami-docker-suitecrm)

**Possible solution**

Jariza proposed the follwing the community forum:

> In order to be able to start the Container with this Data installed, we need to add a parameter to the SuiteCRM Nami Module and adapt the logic to pass the Wizard using this parameter. Then you can pass this parameter with an environment variable when starting the containers.

Thanks in advance. 

Beste regards, 
Stephan

**Comment by juan131** [comment]
Hi @Stephan-Berlin thanks for opening it!

We need to find a way to modify the "passWizard" so we can decided whether to install the demo data or not.

@tompizmor @jotadrilo @dbarranco what do you think about adding this parameter to the NM and modify the "passWizard" logic? Then we can add the parameter to the `suitecrm-inputs.json` file and use environment variables to install it or not when creating the container.

**Comment by jotadrilo** [comment]
Hi there!

This is feasible.

In a first instance, I would say we can just expose a `SUITECRM_DEMO_DATA=yes|no` environment variable and allow the users to get benefits from it.

However, we need to check whether to test demo datasets or not. Note that those datasets (or the wizard input) are likely to change between versions and cause problems too often. We will evaluate this internally.

Does it sound good?

**Comment by Stephan-Berlin** [comment]
Sounds good. Looking forward to the next commit. :)

**Comment by juan131** [comment]
I created an internal task to add this parameter/environment variable to the suiteCRM container.

**Comment by jomisa** [comment]
Its these feature already done?, if so, whats the environment variable

**Comment by juan131** [comment]
This feature hasn't been done yet. It's included in our backlog with low priority so it's likely it'll take some time until we can address it.

Thanks so much for your consideration and patience.

**Comment by shoei101** [comment]
is this still on hold?

**Comment by juan131** [comment]
Yes @shoei101. I just double-checked it, and the associated task is still in our backlog. This task has a low priority, and it's unlikely to be addressed soon.

The container logic was moved to Bash scripts (see https://github.com/bitnami/bitnami-docker-suitecrm#71118-debian-10-r13) recently, and now everything it's public, see:

- https://github.com/bitnami/bitnami-docker-suitecrm/tree/master/7/debian-10/rootfs/opt/bitnami/scripts

Please feel free to contribute to this scripts adding this feature if it's a blocking item for you. We'll be glad to review any PR.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
