### ISSUE TITLE
Docker, firewalld, centos 7

### ISSUE THREAD

**Issue by RobinEd** [bitnami/bitnami-docker-suitecrm#74]
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

the docker0 Interface (and other) do not always go to the trusted zone using either nmcli or firewall-cmd. docker-compose up gives many errors of the type: Couldn't load target `DOCKER'  and Couldn't load target `DOCKER' errors

**Steps to reproduce the issue:**
firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --permanent --zone=trusted --change-interface=docker0
firewall-cmd --get-zone-of-interface=docker0
firewall-cmd --reload
firewall-cmd  --set-log-denied=all
firewall-cmd  --set-log-denied=off
firewall-cmd --list-all
nmcli connection modify docker0 connection.zone trusted
nmcli connection show docker0 | grep zone

docker-compose up

Workarounds in
https://stackoverflow.com/questions/39134551/centos-vm-with-docker-getting-host-unreachable-when-trying-to-connect-to-itself/39211891#39211891
https://unix.stackexchange.com/questions/199966/how-to-configure-centos-7-firewalld-to-allow-docker-containers-free-access-to-th
https://github.com/firewalld/firewalld/issues/195
https://github.com/moby/moby/issues/32138
https://github.com/moby/moby/issues/16816
https://github.com/moby/moby/issues/15948
https://github.com/moby/moby/issues/16137

(especially the last two links) don't work

**Describe the results you received:**

with get-zone of the interface is not always in the trusted zone
with list-all the whole interface and zone can't be seen
with nmcli also not always in the trusted zone
the files created by networkmanager and firewalld change pretty randomly, especially after restarts.

/var/log/messages (with docker-compose up):

Jan 11 13:08:10 localhost kernel: Bridge firewalling registered
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory#012#012Try `iptables -h' or 'iptables --help' for more information.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory#012#012Try `iptables -h' or 'iptables --help' for more information.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -F DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '//' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -F DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -F DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -n -L DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -n -L DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost kernel: ctnetlink v0.93: registering with nfnetlink.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE' failed: iptables: No chain/target/match by that name.
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:08:10 localhost firewalld[540]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT' failed: ipt

service firewalld status -l
Redirecting to /bin/systemctl status  -l firewalld.service
? firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-01-11 13:17:53 CET; 10min ago
     Docs: man:firewalld(1)
 Main PID: 2285 (firewalld)
   Memory: 25.8M
   CGroup: /system.slice/firewalld.service
           +-2285 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i br-c62056a3457c -o br-c62056a3457c -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -i br-c62056a3457c -o br-c62056a3457c -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -i br-c62056a3457c ! -o br-c62056a3457c -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -o br-c62056a3457c -j DOCKER' failed: iptables: No chain/target/match by that name.
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C FORWARD -o br-c62056a3457c -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.19.0.2:443 ! -i br-c62056a3457c' failed: iptables: No chain/target/match by that name.
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-c62056a3457c -o br-c62056a3457c -p tcp -d 172.19.0.2 --dport 443 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.19.0.2 -d 172.19.0.2 --dport 443 -j MASQUERADE' failed: iptables: No chain/target/match by that name.
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.19.0.2:443 ! -i br-c62056a3457c' failed: iptables: No chain/target/match by that name.
Jan 11 13:26:03 136-144-177-45.colo.transip.net firewalld[2285]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

**Describe the results you expected:**

firewalld to set up a firewall and allow traffic to ports 40 and 443

**Additional information you deem important (e.g. issue happens only occasionally):**

When stopping firewalld (systemctl stop firewalld) ports 80 and 443 are reachable

**Version**
```
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:07:19 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:10:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639GiB
Name: 136-144-177-45.colo.transip.net
ID: BXVE:J7DO:YQB3:MYZS:J6SC:3CJO:UQTD:VGWY:4QGP:BVJE:VDLW:NDHO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Centos 7 machine on VM at TransIP
uname -a
Linux 136-144-177-45.colo.transip.net 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dbarranco** [comment]
Hi @RobinEd 

Please, take into account that these GitHub issues are related with errors related to the Bitnami's SuiteCRM docker image. Not issues of external tools.

As this issue is related to the firewall configuration and Docker itself, we do recommend to continue posting in the issues you referenced in your previous post, and use one of the workaround showed in those posts.

Sorry for the inconveniences.
Best regards.
