### ISSUE TITLE
Unable to get SuiteCRM version number

### ISSUE THREAD

**Issue by lid** [bitnami/bitnami-docker-suitecrm#79]
**Description**

In `/index.php?module=Home&action=About` the version number of SuiteCRM is missing.

**Steps to reproduce the issue:**

1. Navigate to `/index.php?module=Home&action=About`

**Describe the results you received:**

The SuiteCRM version number is not displayed, only the string "Version" followed by a newline and the Sugar Version.

**Describe the results you expected:**

SuiteCRM version number is displayed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Relevant error log:
```
[Tue Mar 27 06:27:49.506933 2018] [:error] [pid 339] [client 10.158.2.93:60822] PHP Warning:  include(suitecrm_version.php): failed to open stream: No such file or directory in /bitnami/suitecrm/modules/Home/About.php on line 43, referer: https://x.x.x.x/index.php?module=Documents&action=DetailView&record=67d6a611-c95a-7842-9a63-5ab9e2802dbb
[Tue Mar 27 06:27:49.506977 2018] [:error] [pid 339] [client 10.158.2.93:60822] PHP Warning:  include(): Failed opening 'suitecrm_version.php' for inclusion (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/modules/Home/About.php on line 43, referer: https://x.x.x.x/index.php?module=Documents&action=DetailView&record=67d6a611-c95a-7842-9a63-5ab9e2802dbb
[Tue Mar 27 06:27:49.506986 2018] [:error] [pid 339] [client 10.158.2.93:60822] PHP Notice:  Undefined variable: suitecrm_version in /bitnami/suitecrm/modules/Home/About.php on line 51, referer: https://x.x.x.x/index.php?module=Documents&action=DetailView&record=67d6a611-c95a-7842-9a63-5ab9e2802dbb
```

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

- Output of `docker info`:

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: RD4F:SZVH:6BJD:RLGW:QIVX:OCXK:ZAAJ:DR3T:NPWD:M2IP:MJ42:OEBT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 54
 Goroutines: 83
 System Time: 2018-03-27T06:46:47.5221233Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Thanks for reporting it. We have included it in our backlog. As the impact of the issue is limited and not critical, there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

In the meantime, you can use this workaround:
```
sed -i -e 's/suitecrm_version\.php/\/opt\/bitnami\/suitecrm\/suitecrm_version\.php/g' /bitnami/suitecrm/modules/Home/About.php
```

With the above command you are replacing
```
include 'suitecrm_version.php';
```
by
```
include '/opt/bitnami/suitecrm/suitecrm_version.php';
```
in `/bitnami/suitecrm/modules/Home/About.php`

We will update this issue as soon as we have more news.

**Comment by namgivu** [comment]
I have the same issue today with latest tagged container-image `image: 'bitnami/suitecrm:latest'`

**Comment by carrodher** [comment]
I just tried it on `7.10.4-r30` (released 7 hours ago) and the workaround works fine. After running the `sed` command you only need to reload the browser page and the version appears:
![screen shot 2018-06-06 at 12 53 13](https://user-images.githubusercontent.com/13216600/41034033-a550342c-6988-11e8-96ce-4b34efae4630.png)

**Comment by namgivu** [comment]
@carrodher Thanks Carrodher, I'll try again. By the way, how to access the API? I follow this guide but it seems not working https://docs.suitecrm.com/developer/api/version-8/

**Comment by carrodher** [comment]
Can you try using an Incognito Window in your browser?

**Comment by juan131** [comment]
Hi everyone

We just addressed this issue on the latest release of this docker image (**7.10.7-r35**). As you can check on the screenshot below, the version is displayed properly now:

![screen shot 2018-08-14 at 16 38 45](https://user-images.githubusercontent.com/6740773/44098498-a726b832-9fe0-11e8-874e-9b7eb46d9afb.png)


Please feel free to try the new image and reopen the issue in case you continue facing issues with the version.
