### ISSUE TITLE
Exception with Read-only file in Volumes

### ISSUE THREAD

**Issue by STK913** [bitnami/bitnami-docker-suitecrm#81]
**Description**

Hello,

I'm using your SuiteCRM Docker and overloading the config_override.php read-only file with Docker volumes, but I have an exception that appears at installation time:
```
28/03/2018 13:41:48nami    INFO  Initializing suitecrm
28/03/2018 13:41:49suitecr INFO  suitecrm has being already initialized, restoring...
28/03/2018 13:41:49suitecr INFO  Setting extra configuration...
28/03/2018 13:41:49suitecr INFO  Cleaning up folders..
28/03/2018 13:41:49suitecr INFO  Configuring Cron Jobs...
28/03/2018 13:41:49suitecr INFO  Configuring permissions...
28/03/2018 13:42:59Error executing 'postInstallation': EROFS: read-only file system, chown '/bitnami/suitecrm/config_override.php'
```

I also modified the Configurator.php and installSystemCheck.php to avoid writing to a read-only file, but apparently this exception is generated by your Stack or Package.
Can you tell me where you are configuring permissions in the code and if there is a workaround for this problem please?

docker-compose :
```
volumes:
- /docker/volumes/suitecrm/installSystemCheck.php:/bitnami/suitecrm/install/installSystemCheck.php:ro
- /docker/volumes/suitecrm/Configurator.php:/bitnami/suitecrm/modules/Configurator/Configurator.php:ro
- /docker/volumes/suitecrm/config_override.php:/bitnami/suitecrm/config_override.php:ro
```

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
 ```

- Output of `docker info`:

```
Containers: 61
 Running: 53
 Paused: 0
 Stopped: 8
Images: 81
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 549
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e542717e2424497b75147314bad948ea3763c14425
runc version: 9c2d8d184e4225da67c95244282adf1422228
init version: 945e64a
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.44GiB
Name: debianprod
ID:
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Rancher

**Comment by STK913** [comment]
I just noticed that the config_override.php file was not supported. Try to populate a SAML configuration and you will see that the file does not override the default configuration (config.php). In addition, when you return to index.php?module=Administration&action=PasswordManager, the contents of the file are deleted. I let you create a ticket for this problem. I'm going to find another image.

**Comment by tompizmor** [comment]
Hi @STK913,

I was able to reproduce the issue. It seems the config_override.php file is not working fine. Not sure if this should work on SuiteCRM or is it just a SugarCRM feature. Did you find somewhere that is not supported or it is just that doesn't work?

> Can you tell me where you are configuring permissions in the code and if there is a workaround for this problem please?

About above question, you can see the logic inside the container in these files:

- _/root/.nami/components/com.bitnami.suitecrm/main.js_
- _/root/.nami/components/com.bitnami.suitecrm/herlpers.js_

The only way to modify that logic is to start the container overriding the entrypoint, exect into the container, modify the logic and then execute the original entrypoint.

**Comment by STK913** [comment]
Hello,

The config_override.php file is well supported by SuiteCRM (including SAML). We use version 7.10 in production.
I noticed the following anomalies on your Stack that do not exist on the official version of SuiteCRM:
- The configuration is not saved in the config_override.php file when modifying the parameters in the admin interface: index.php?module=Administration&action=PasswordManager
- If you create the file config_override.php manually, the configuration is never retrieved by SuiteCRM.

However, we can include the configuration in the config.php file, but we can not modify it from the interface.

It would be great if you could handle the config_override.php file quickly.

Thank you for your reply.

**Comment by tompizmor** [comment]
Hi @STK913,

This is just a note to let you know that we are aware of the issue and will try to fix it for future releases.

**Comment by juan131** [comment]
HI @STK913 

We modified the permissions configuration on the latest release (**7.10.7-r35**) of this docker image. That should have fix the issue with **config_override.php** and, when modifying the configuration through the Admin panel, it should be saved on the persisted file **/bitnami/suitecrm/config_override.php**.

Please feel free to use this new version and let us know if that solves your issue.
