### ISSUE TITLE
Cannot edit columns in list view/module builder

### ISSUE THREAD

**Issue by lid** [bitnami/bitnami-docker-suitecrm#82]
**Description**

In Studio/Module Builder, attempts to the columns in List View layouts fails. Specifically, clicking the pencil/edit icon to edit the column width (necessary to add columns to Default/Available if they do not already have a width specified) seems to cause an error, and redirects the browser to a page of JSON, rather than opening a tab with a field to set the column width.

**Steps to reproduce the issue:**

1. Open Studio->Contacts->Layouts->List View
2. Click the pencil/edit icon to change the column width

**Describe the results you received:**

You are redirected to a page of JSON(ish). If you navigate back to the List View layout configurator, all columns have been moved to Hidden.

**Describe the results you expected:**

A tab opens with a field to edit the column width; columns are not moved to Hidden.

**Additional information you deem important (e.g. issue happens only occasionally):**

Not reproducible on the 7.9.9 AWS stack, but is reproducible on the 7.10.2-1 AWS stack. An associated error (not sure if it's relevant) in the apache logs:
```
[Mon Apr 09 16:01:38.959910 2018] [:error] [pid 336] [client x.x.x.x:53032] PHP Warning:  copy(custom/history/modulebuilder/packages/DMM2/modules/DMM2/metadata/detailviewdefs.php): failed to open stream: No such file or directory in /bitnami/suitecrm/modules/ModuleBuilder/parsers/views/History.php on line 186, referer: https://y.y.y.y/index.php?module=ModuleBuilder&action=index&type=mb```
```

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.15
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.03.1-ce
  API version:	1.27 (minimum version 1.12)
  Go version:	go1.7.5
  Git commit:	c6d412e
  Built:	Tue Mar 28 00:40:02 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log:
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
Kernel Version: 4.9.75-rancher
Operating System: RancherOS v1.1.3
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.766GiB
Name: z.z.z.z
ID: YAN7:NLWQ:62GQ:6TJO:MCYE:EGTW:6P7M:YALW:VGTO:6ZGF:VW3Y:DMQ7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by lid** [comment]
Looks like the hotfix was not applied to the upgraded container because the affected file (`modules/ModuleBuilder/tpls/listView.tpl`) is in the `/bitnami/suitecrm/modules` path, which is persisted to the volume. This seems to imply that upstream updates to any files in the modules folder won't stick... what's the best way to handle this?

**Comment by juan131** [comment]
Hi @lid 

As you mentioned all the modules are persisted. Therefore, even if you upgrade your image, no changes will be applied there. 

In order to upgrade every component, you'd need to upgrade SuiteCRM using the Wizard:

https://docs.suitecrm.com/admin/installation-guide/using-the-upgrade-wizard

> Please note you'd need to perform a "composer update" first

```docker-compose exec suitecrm bash
docker-compose exec suitecrm composer update
```
