### ISSUE TITLE
Some SutieCRM settings cannot be changed

### ISSUE THREAD

**Issue by ashak** [bitnami/bitnami-docker-suitecrm#84]
**Description**

Unable to change some suitecrm settings

**Steps to reproduce the issue:**

1. deploy suitecrm to docker swarm
2. login to suitecrm using default admin credentials
3. In the top right, Hover over Administrator until the menu pops up, select Admin
4. On the new page click 'System Settings'
5. Change 'Lead Converstion Options' to something else
6. Click 'Save'
7. On the new page click 'System Settings' again
8. See that 'Lead Conversion Options' has returned to its previous setting
9. There are similar other possibly related things i've tried. Such as changing the currency in the Locale settings.

**Describe the results you received:**

The changes to some settings do not save.

**Describe the results you expected:**

The settings changes will save.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 20
 Running: 1
 Paused: 0
 Stopped: 19
Images: 5
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: i1hqyquhac70vhcn2e1gf11yy
 Is Manager: true
 ClusterID: z5pc88o5cithmx6zexqdntw27
 Managers: 2
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.29.236.41
 Manager Addresses:
  172.29.236.41:2377
  172.29.236.42:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.35GiB
Name: hostname.domain.tld
ID: MVDM:VENC:AMUB:PQXR:UJ5X:E4O7:SNKW:ZT2T:M6PN:BBHO:SZX2:U4VT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical machines running fully up to date CentOS 7

**Comment by juan131** [comment]
I was able to reproduce the issue. 

Probably related with the error below I found on Apache logs:

```
PHP Warning:  touch(): Unable to create file config_override.php because Permission denied in /opt/bitnami/suitecrm/modules/Configurator/Configurator.php on line 214
```

However, I could not fix the issue setting a different permissions configuration. We'll need to investigate the issue deeply. Thanks for reporting it! I'll open a task to work on it.

**Comment by juanluisbaptiste** [comment]
Hola @juan131 

Any news on this ? I'm seeing this issue too, for now I'm manually editing config.php, but not always is clear what I need to change when editing that file so it would be nice to see this fixed.

**Comment by juanluisbaptiste** [comment]
Something I just noticed, settings are being saved to **config_override.php**, but they are ignored, it is only taking what it is on **config.php**.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

We have at task included in our backlog. However, there are no immediate plans to work on it. 
Nevertheless, it will be considered for future application versions.

> Something I just noticed, settings are being saved to config_override.php, but they are ignored, it is only taking what it is on config.php.

The configuration file used is the one which is persisted at **/bitnami/suitecrm/config.php**. You should edit that file in order to change the settings.

**Comment by Coolfeather2** [comment]
being unable to change settings is a issue, interested in getting this fixed

**Comment by javsalgar** [comment]
We will update this ticket as soon as we have news on it

**Comment by daveblackuk** [comment]
We have the same issue with a new build using a volume or local storage. This is now a priority issue for us - can this be accelerated ?

we cannot change password reset parameters, this is a breach of our security policies

we cannot set a strength policy on passwords, this also breaches our security policies

we cannot use system generated passwords, this also breaches our security policies

we cannot change currency in locale or other configurations - given we are a UK based entity we trade in GBP not USD

Does anyone have a manual workaround until this is fixed?

**Comment by juan131** [comment]
Hi @daveblackuk 

The task associated to this issue is currently being considered to be addressed in the next week. We will update this thread as soon as we have more news.

**Comment by juan131** [comment]
HI everyone,

We modified the permissions configuration on the latest release (**7.10.7-r35**) of this docker image. We modified the permissions on the file **config_override.php** and, when modifying the configuration through the Admin panel, the changes should be saved on the persisted file **/bitnami/suitecrm/config_override.php**.

That should have fix the issue when editing the Admin settings through the admin panel. 

Here I attach some screenshots and commands to show the new behaviour:

- First I check the current content of **config_override.php**:

```
$ docker-compose exec suitecrm cat /bitnami/suitecrm/config_override.php
<?php
/***CONFIGURATOR***/
$sugar_config['default_export_charset'] = 'ISO-8859-1';
$sugar_config['disable_persistent_connections'] = false;
/***CONFIGURATOR***/
```

- Then, I change some settings through Admin Panel:

![screen shot 2018-08-14 at 16 43 20](https://user-images.githubusercontent.com/6740773/44098776-55af4ce8-9fe1-11e8-8f0a-303cb32fdab1.png)

- As you can check, those changes are saved on the **config_override.php** file:

```
$ docker-compose exec suitecrm cat /bitnami/suitecrm/config_override.php
<?php
/***CONFIGURATOR***/
$sugar_config['default_export_charset'] = 'ISO-8859-1';
$sugar_config['disable_persistent_connections'] = false;
$sugar_config['lead_conv_activity_opt'] = 'move';
$sugar_config['default_module_favicon'] = false;
$sugar_config['dashlet_auto_refresh_min'] = '30';
$sugar_config['stack_trace_errors'] = false;
/***CONFIGURATOR***/
```

- Finally, I try to edit again the settings and check that my previous changes've been saved:

![screen shot 2018-08-14 at 16 45 44](https://user-images.githubusercontent.com/6740773/44098842-8568dc24-9fe1-11e8-88fe-ab2004cffce8.png)


Please feel free to use this new version and let us know if that solves your issue.

**Comment by juanluisbaptiste** [comment]
It is not working for me, `config_override.php` is correctly modified but the GUI still shows old value. It seems it isn't loading that override file.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

It takes some time to be updated on te GUI. I noticed it's updated after 20-30 seconds... Could you please confirm it also works to you?

**Comment by Coolfeather2** [comment]
Works Great, thanks for the update

 - make sure you are using r35 @juanluisbaptiste

**Comment by juanluisbaptiste** [comment]
@juan131 

> It takes some time to be updated on te GUI. I noticed it's updated after 20-30 seconds... Could you please confirm it also works to you?

Yes it works after the delay, but why does that happen ??

**Comment by Coolfeather2** [comment]
I had no delay, browser cache?

**Comment by juan131** [comment]
Hi @Coolfeather2 @juanluisbaptiste 

I honestly had no time to investigate deeply the reason about the delay. I considered it a minor issue since it's not very common you change the site settings so frequently.

**Comment by juanluisbaptiste** [comment]
Hi,

I'm having again this issue on 7.11.6, I'm trying to enable the forgot your password feature checkbox but after clicking save and opening again the password management settings, the forgot your pasword checkbox is again unchecked.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

In the past we experienced some delay in the UI, it took between 20-30 seconds to update the values despite they were already changed in the `config_override.php` file.

Could you please confirm it that's your case @juanluisbaptiste ? Could you also check if the settings are updated in the `config_override.php` file?

**Comment by juanluisbaptiste** [comment]
@juan131 , yes I remember and indeed that was the case, but why is this ? its very annoying !

**Comment by juan131** [comment]
I'm not sure @juanluisbaptiste 

But I guess it's a matter of cache @juanluisbaptiste in the browser.

**Comment by juanluisbaptiste** [comment]
@juan131 I don't think that is the issue, if you open the browser console, tick the disable cache option and then go and save a setting and go back to it is still empty. If it was a matter of browser cache then if you the cache disabled then there's no cache time set to wait.

**Comment by juan131** [comment]
I can't tell @juanluisbaptiste 

Probably you might get more info about why this annoying behaviour is happening in the SuiteCRM forums:

- https://community.suitecrm.com/
