### ISSUE TITLE
Lucene index as separate Docker service

### ISSUE THREAD

**Issue by jadster** [bitnami/bitnami-docker-suitecrm#86]
**Description**

In the spirit of Docker I'd think it might be a good idea to "outsource" the Lucene index process (called Advanced Open Discovery or AOD in SuiteCRM lingo) into its own Docker container.

Have you given this any thought?
Would that be hard to do without completely changing SuiteCRM code?

**Comment by marcosbc** [comment]
Hi,

The Zend_Search_Lucene project is derived from the Apache Lucene project and the index format is compatible with certain Lucene versions.
However, it is designed to fully integrate into the application's source code, and does not offer any external access to the search service.
Therefore, we don't think it's possible to separate it as another Docker service without rewriting the AOD code (unless you use shared volumes for storing Lucene index files and the program, which is a bit hacky).

In any case, we recommend you to contact directly with the [SugarCRM community](https://community.sugarcrm.com/welcome), they might be interested in the idea of supporting an external Lucene/Solr server.
