### ISSUE TITLE
HTTPS access: SSL certifiactes 

### ISSUE THREAD

**Issue by jadster** [bitnami/bitnami-docker-suitecrm#87]
**Description**

How would we best go about setting up an SSL certificate for https access?

Must we do this manually after the container is built?

**Comment by juan131** [comment]
Hi @jadster 

You can create them manually once the container is built or you can mount them. 

By default, this image includes some "dummy" certificates (self-signed) as you can check by running:

```
$ docker-compose exec suitecrm cat /opt/bitnami/apache/conf/vhosts/suitecrm-https-vhost.conf
AddType application/x-httpd-php .php

<VirtualHost  127.0.0.1:443  _default_:443>
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /opt/bitnami/suitecrm
  <Directory "/opt/bitnami/suitecrm">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.php


  </Directory>
  Include /opt/bitnami/apache/conf/vhosts/htaccess/suitecrm-htaccess.conf
</VirtualHost>
```

Therefore, you can mount

**Comment by jadster** [comment]
Thanks.

I'm still confused about this:
Assuming I'm running apache on the host and have suitecrm running in a docker container.
Now I want ssl access to Suitecrm.

Would I set up the virtualhost with SSL-certificates in the host apache installation or in the docker container apache installation?

**Comment by marcosbc** [comment]
Hi @jadster,

Please note that out SuiteCRM container already uses Apache to serve the application. You shouldn't need to use another Apache at the host machine.

However, if you still prefer to use this architecture, the simplest solution would consist in enabling SSL on the host's Apache (not in the container), in a similar way to how Juan mentioned: Find [here](https://docs.bitnami.com/aws/components/apache/#how-to-enable-https-support-with-ssl-certificates) the instructions for a Bitnami Apache installation.
With that configuration, you would proxy to the container's port 80.
