### ISSUE TITLE
Easy Fix - NTLM Phpmailer SendMail using mhash instead of hash on image with PHP 7

### ISSUE THREAD

**Issue by martin-kieliszek** [bitnami/bitnami-docker-suitecrm#89]
**Description**

Using `docker.io/bitnami/suitecrm:7.10.9-debian-9` 
that contains `PHP 7.0.32 (cli)`

When adding an outbound email that points to an MS Exchange with SMTP authentication, the SuiteCRM codebase calls upon this file; `/opt/bitnami/suitecrm/include/phpmailer/extras/ntlm_sasl_client.php` in order to prepare the NTLM hash for authentication. This file references the depreceated (and absent from the container) `mhash` module. Instead, it should reference the newer hash module. 

Due to this mismatch in php version and old codebase, all attempts to connect to MS Exchange with SMTP Auth fails due to mhash missing.

Have modified codebase within container on the fly and confirmed changing all references of mhash and any respective MHASH_MD4 constants in place of hash and 'md4' respectively, fixes the issue.
 
**Steps to reproduce the issue:**

1. Pull docker image version as per above - wait for it to load. Login to SuiteCRM as admin.
2. Go to Profile Icon > Admin > Outbound Email
3. Click on sytem to modify this as a new outbound email
4. Fill in form details as per normal - targetting an MS exchange mail server that requires SMTP auth (and hence, the codebase to prepare an NTLM hash via the phpmailer extra codebase).
5. Click Send Test Email
6. Observe a failure to send email. Click show log button to observe inability to proceed forward to sending email due to `mhash module missing`. (Is actually depcreated and on this PHP version within the container, should be modified to hash)

**Describe the results you received:**

Fail with SMTP Log error message describing missing `mhash` module.

**Describe the results you expected:**

Successful email sent as a result of being able to proceed passed "AUTH NTLM <HASH>" step within the SMTP logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

Is fixed when I manually modify the code base to use `hash` module in all place of all string references to `mhash` and modifying the line with reference to `MHASH_MD4` to `$md4 = hash('md4', $unicode);`

**Version**

- Output of `docker version`:

```
$ docker --version
Docker version 17.03.2-ce, build f5ec1e2
```

- Output of `docker info`:

```
NA
```

- Output of `docker-compose version` (if applicable):

```
NA
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by tompizmor** [comment]
Hi @martin-kieliszek,

If I have understood the issue, to me it seems to be a bug in the SuiteCRM application code.
According to [this page](https://docs.suitecrm.com/admin/compatibility-matrix/), SuiteCRM should be compatible with PHP 7.0.

Have you reported this issue to the SuiteCRM team?
