### ISSUE TITLE
How can I access json rest api?

### ISSUE THREAD

**Issue by tapgabee** [bitnami/bitnami-docker-suitecrm#92]
How can I access json rest API like SuitecCRM [document?](https://docs.suitecrm.com/developer/api/version-8/json-api/)

**Comment by juan131** [comment]
Hi @tapgabee 

Did you follow the guide below to configure the API on your SuiteCRM container?

https://docs.suitecrm.com/developer/api/version-8/configure-suitecrm/

The `lib/API/` directory can be found on this container under `/opt/bitnami/suitecrm/lib/API`. You can access to it by running:

```
$ docker-compose up -d
$ docker-compose exec suitecrm bash
# cd /opt/bitnami/suitecrm/lib/API
```

> Please note you that 'Mod Rewrite' is already installed and configured on Apache
