### ISSUE TITLE
data base

### ISSUE THREAD

**Issue by ghinaaltal** [bitnami/bitnami-docker-suitecrm#94]
Hello guys,
please can anyone help me!
I am the admin of a new wordpress website that is still new and have no post or news, the website is hosted on Linux, Ubuntu server. I noticed lately that the data base of the website is increasing rapidly day by day without performing any thing on the site..
and the wp_options table is full of this records:
_wp_session_expires_71d531600d0bdfdde3f08b1f580c5c7b
_wp_session_9998b4cdeb00519b1bced28c43702bef
_wp_session_expires_9998b4cdeb00519b1bced28c43702bef
_wp_session_ffe442604b947bb0893a03d3d7d70c73
_wp_session_41f9a4c1866351f75cef324c80014899
_wp_session_expires_ffe442604b947bb0893a03d3d7d70c73
_wp_session_expires_41f9a4c1866351f75cef324c80014899
_wp_session_9735cdb65c9e46c6a7e54ddefd76f0a7
_wp_session_expires_9735cdb65c9e46c6a7e54ddefd76f0a7
_wp_session_2530eafcd5d0790982c17f4d6c02500b
_wp_session_expires_2530eafcd5d0790982c17f4d6c02500b
_wp_session_590b5fca3e1b057511f5b0822edb969e
_wp_session_expires_590b5fca3e1b057511f5b0822edb969e
_wp_session_7b8d8eda21fe050e1067627a50c58571
_wp_session_expires_7b8d8eda21fe050e1067627a50c58571

how can I solved this issue, I highly appreciate any help there..
and please to show me in details how to solve it as am new in websites

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
  As you are new to websitest, I would suggest you to look first into wordpress documentation. The wp_options table is documented [here](https://codex.wordpress.org/Database_Description).
  It is normal because wordpress assing a session to each user that visit the site. You should control that the expired sessions are being purged.

Best Regards,

**Comment by ghinaaltal** [comment]
Hi rafa,
but the site is new, and no traffic on it..
the database increased from 4MB to 33MB during two days, even though there's no hits on the site nor any published content on it.

**Comment by ghinaaltal** [comment]
@rafariossaa

**Comment by ghinaaltal** [comment]
@rafariossaa ,,Also the  load average: 0.51, 0.35, 0.30 is like that
is that normal for a new site with no hits site?

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
  Sorry for the delay.
  Could you recheck that in the apache access log is there no access ?
  Could you check if the size of the table is stable? I mean it keep not growing. Wordpress has internals jobs that could create new sessions.

Thanks forehand,
Rafael Rios

**Comment by ghinaaltal** [comment]
@rafariossaa 

here is the database tables size
 Table                                           | Size (MB) |
+-------------------------------------------------+-----------+
| wp_options                                      |    228.31 |
| wp_posts                                        |      2.31 |
| wp_postmeta                                     |      0.68 |
| wp_revslider_css                                |      0.09 |
| wp_revslider_slides                             |      0.07 |
| wp_wc_download_log                              |      0.05 |
| wp_es_subscriber_ips                            |      0.03 |
| wp_wc_webhooks                                  |      0.03 |
| wp_usermeta                                     |      0.02 |
| wp_wplc_offline_messages                        |      0.02 |
| wp_es_sentdetails                               |      0.02 |
| wp_es_notification                              |      0.02 |
| wp_es_emaillist                                 |      0.02 |
| wp_es_deliverreport                             |      0.02 |
| wp_wplc_chat_sessions                           |      0.02 |
| wp_wplc_webhooks                                |      0.02 |
| wp_wplc_chat_msgs                               |      0.02 |
| wp_terms                                        |      0.01 |
| wp_revslider_sliders                            |      0.01 |
| wp_termmeta                                     |      0.01 |
| wp_comments                                     |      0.01 |
| wp_users                                        |      0.01 |
| wp_term_taxonomy                                |      0.01 |
| wp_yoast_seo_links                              |      0.01 |
| wp_term_relationships                           |      0.01 |
| wp_woocommerce_sessions                         |      0.00 |
| wp_woocommerce_shipping_zone_locations          |      0.00 |
| wp_commentmeta                                  |      0.00 |
| wp_yoast_seo_meta                               |      0.00 |
| wp_woocommerce_shipping_zone_methods            |      0.00 |
| wp_woocommerce_shipping_zones                   |      0.00 |
| wp_woocommerce_api_keys                         |      0.00 |
| wp_woocommerce_tax_rates                        |      0.00 |
| wp_woocommerce_downloadable_product_permissions |      0.00 |
| wp_woocommerce_tax_rate_locations               |      0.00 |
| wp_smush_dir_images                             |      0.00 |
| wp_links                                        |      0.00 |
| wp_woocommerce_attribute_taxonomies             |      0.00 |
| wp_revslider_static_slides                      |      0.00 |
| wp_woocommerce_payment_tokens                   |      0.00 |
| wp_woocommerce_payment_tokenmeta                |      0.00 |
| wp_revslider_navigations                        |      0.00 |
| wp_woocommerce_order_items                      |      0.00 |
| wp_revslider_layer_animations                   |      0.00 |
| wp_woocommerce_order_itemmeta                   |      0.00 |
| wp_woocommerce_log                              |      0.00 


and yeah it's stable … but when I take a backup of the database it get large day by day
as follows:
-rw-rw-r-- 1 bitnami bitnami 100870804 Nov 11 08:50        db_2018-11-11.sql
-rw-rw-r-- 1 bitnami bitnami 108491545 Nov 12 10:41        db_2018-11-12.sql
-rw-rw-r-- 1 bitnami bitnami 115751279 Nov 13 10:41        db_2018-11-13.sql
-rw-rw-r-- 1 bitnami bitnami 123402078 Nov 14 10:41        db_2018-11-14.sql
-rw-rw-r-- 1 bitnami bitnami   4756926   Nov 15 10:27        db_2018-11-15.sql
-rw-rw-r-- 1 bitnami bitnami   5100658   Nov 22 08:52        db_2018-11-22.sql

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
  I would like to take a look to the config files,  You do not need to post the configuration file here, we have a Support Tool that will gather relevant information for us to review your configuration. Could you please download and execute it on the machine where the stack is running by following the steps described in the guide below?[

How to Run the Bitnami Support Tool](https://docs.bitnami.com/general/how-to/understand-bnsupport/)

  By the way, I guess the problem is that the GET you have from what looks like a loadbalancer (172.26.13.122, 172.26.37.183) are creating tons of sessions. This sessions should be purged by the cron.php.

Thanks forehand.
Rafael Rios

**Comment by ghinaaltal** [comment]
Hi @rafariossaa ,

I follow the steps in the guide and activated Bitnami Support Tool, here is the code: 
2dac57e1-3c49-ca78-4616-a38978d53bca

waiting your feedback

Thank you...

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
   I can not see relevant information on the BST report.
  Could you also paste the wp-config.php file? As this file contains password, please substitue the secret information by XXXX.

  Also, could you install and activate the [wp-control](https://wordpress.org/plugins/wp-crontrol/) plugin ?. Then under Tools -> Cron Events there will be all the crons that are ment to be executed. Could you paste a screenshot of this screen ?.
  `delete_expired_transients` is the one that should remove that info from the table. You can try to execute it manually (through 'Run now' link at the end of the row) and check if the data from the table is removed.

Best regards,
Rafael Rios.

**Comment by ghinaaltal** [comment]
Hi @rafariossaa here is the wp-config.php file, I can't attached as file so here is it's contents:

<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */


define('FS_METHOD', 'direct');

define( 'AS3CF_SETTINGS', serialize( array(
    'provider' => 'aws',
    'access-key-id' => 'xxxxxxxxxxxxxx',
    'secret-access-key' => 'xxxxxxxxxxxxxxxxxxxxx',
) ) );

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'xxxxxx');

/** MySQL database username */
define('DB_USER', 'xxxxxxx');

/** MySQL database password */
define('DB_PASSWORD', 'xxxxxxxxxxxxxxxxxx');

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8mb4');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY',         '');
define('SECURE_AUTH_KEY',  '');
define('LOGGED_IN_KEY',    '');
define('NONCE_KEY',        '');
define('AUTH_SALT',        '');
define('SECURE_AUTH_SALT', '');
define('LOGGED_IN_SALT',   '');
define('NONCE_SALT',       '');

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix  = 'wp_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the Codex.
 *
 * @link https://codex.wordpress.org/Debugging_in_WordPress
 */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

**Comment by ghinaaltal** [comment]
@rafariossaa, here is a screen shot for the wp_control plugin also :

![wp_control](https://user-images.githubusercontent.com/45161211/49134278-b902b980-f2eb-11e8-8966-21379a212c44.JPG)

**Comment by ghinaaltal** [comment]
@rafariossaa I dont't have delete_expired_transients in above secreen shot

**Comment by ghinaaltal** [comment]
@rafariossa I run delete_expired_transients cron job as requested, see below shot
![capture](https://user-images.githubusercontent.com/45161211/49137616-a4c3ba00-f2f5-11e8-95d7-547112b9d137.JPG)

but the it didn't work, the data base size still increases as follows:

-rw-rw-r-- 1 bitnami bitnami 100870804  Nov 11 08:50   db_2018-11-11.sql
-rw-rw-r-- 1 bitnami bitnami 108491545  Nov 12 10:41   db_2018-11-12.sql
-rw-rw-r-- 1 bitnami bitnami 115751279  Nov 13 10:41   db_2018-11-13.sql
-rw-rw-r-- 1 bitnami bitnami 123402078  Nov 14 10:41   db_2018-11-14.sql
-rw-rw-r-- 1 bitnami bitnami   4756926    Nov 15 10:27    db_2018-11-15.sql
-rw-rw-r-- 1 bitnami bitnami   5799919   Nov 25 11:51    db_2018-11-25.sql
-rw-r--r-- 1 bitnami bitnami   5627691    Nov 26 07:14     db_2018-11-26.sql
-rw-rw-r-- 1 bitnami bitnami   5757642   Nov 27 07:10    db_2018-11-27.sql
-rw-rw-r-- 1 bitnami bitnami   6521941    Nov 28 08:07    db_2018-11-28.sql

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
  Could you check if the sessions related rows has been deleted from wp_options ?
  You have several plugins installed and they usually use that table. Maybe the problem produce by one them.

Best Regards,
Rafael Rios

**Comment by ghinaaltal** [comment]
Morning @rafariossaa, I checked them, they still existed and created daily …
I send you a screen shot above for the table, and the active plugins in my site...

How could I know which plugin is causing this issue ??

**Comment by ghinaaltal** [comment]
Hi @rafariossaa  I have notice that when typing the "top" command that mysql.bin process is consuming large number of CPU and that loading the load average time to be increased in some time...

do you have any idea how can I avoid this please?

**Comment by ericmann** [comment]
The keys are created by a much older version of the WP Session Manager plugin, which is used to cache anonymous user sessions in the WordPress database (versus the filesystem, which is the PHP default).

Considering you don't have that plugin listed in your set of active plugins, my guess is that the author of one of your _other_ plugins merely copy-pasted an older version of the library into their own codebase, which is what's causing the problem.

I would suggest searching the code of your site for `wp_session` to identify the plugin that's doing it. It could also be your theme.

Either way - you should reach out to the maintainer of the plugin cluttering your database and ask them to update their codebase to use a more recent version of the underlying library.

**Comment by rafariossaa** [comment]
Hi @ericmann,
   Thank you very much for this information and helping us to resolve this issue.

Best regards,
Rafael Rios Saavedra

**Comment by ghinaaltal** [comment]
> The keys are created by a much older version of the WP Session Manager plugin, which is used to cache anonymous user sessions in the WordPress database (versus the filesystem, which is the PHP default).
> Considering you don't have that plugin listed in your set of active plugins, my guess is that the author of one of your other plugins merely copy-pasted an older version of the library into their own codebase, which is what's causing the problem.
> I would suggest searching the code of your site for wp_session to identify the plugin that's doing it. It could also be your theme.
> Either way - you should reach out to the maintainer of the plugin cluttering your database and ask them to update their codebase to use a more recent version of the underlying library.

@ericmann  yeah, but still I want to know which plugin is casing this sessions !!! I am not a coder so how can I do that, I tried one time to deactivate all  plugins but the site goes down.

**Comment by ghinaaltal** [comment]
> Hi @ericmann,
> Thank you very much for this information and helping us to resolve this issue.
> Best regards,
> Rafael Rios Saavedra
@rafariossaa  the issue still not solved.

**Comment by rafariossaa** [comment]
Hi @ghinaaltal,
  I don't know if this is possible for you, but, as it this your production site, I would suggest you to replicate the site and use this replica to develop/debug.
  To avoid misunderstanding, I am not considering this issue solved. I was just thanking @ericmann for his contribution.

Best regards,
Rafael Rios Saavedra.
