### ISSUE TITLE
Backing up database on Mac

### ISSUE THREAD

**Issue by Wayne-II** [bitnami/bitnami-docker-suitecrm#96]
**Description**

There doesn't appear to be docs covering a way to backup the MariaDB on Mac.

https://github.com/bitnami/bitnami-docker-mariadb#step-2-stop-and-backup-the-currently-running-container

However Docker for Mac runs on a VM, so you have to use the following command to get the volumes.
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty

**Steps to reproduce the issue:**

1. Install bitnami/suitecrm:latest
2. backup MariaDB volume

**Describe the results you received:**

Cannot backup.

**Describe the results you expected:**

Documented procedure for backing up for all officially supported Docker hosts.

**Additional information you deem important (e.g. issue happens only occasionally):**

I suspect I'm going to run into the same issue with docker-toolbox on WIndows 7

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 9
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: MEZX:EVQ3:F2DV:HPAI:U5FO:RFCC:4Q4O:3QB7:P4SE:NVEX:FJUQ:VYHA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 54
 System Time: 2019-01-15T16:34:40.364346536Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for Mac migrating to Docker Toolbox for Windows.

**Comment by juan131** [comment]
Hi @Wayne-II 

The guide you shared assumes you mounted a host's volume instead of using [docker volumes](https://docs.docker.com/storage/volumes/). 

I'll share this issue with the Docs Team so they can work on documenting how to backup the database in the different officially supported Docker hosts.

PD: you can also use a MySQL client and backup your database. More info in the link below:

https://docs.bitnami.com/general/infrastructure/mariadb-galera/administration/backup-restore-mysql-mariadb/
