### ISSUE TITLE
Unable to change/set user passwords

### ISSUE THREAD

**Issue by kaptainkommie** [bitnami/bitnami-docker-suitecrm#97]
**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml > docker-compose.yml
2. docker-compose up -d
3. Once initial install is finished, login to SuiteCRM as the default "user" with default password "bitnami"
4. Change password for default "user", providing "bitnami" as the current password. Save changes.
5. Logout of SuiteCRM
6. Attempt to login with new password. Fails.
7. Login with default password "bitnami" still works.

**Describe the results you received:**
Password change does not get saved to the database. This was verified by checking the database and noting, in the case of the default admin "user" the password_hash has not changed. Looking at a newly created user, the password_hash field is empty. I have tried updating password both as a logged in user by going to "Profile" and forcibly as the "Admin" user. Neither works.

**Describe the results you expected:**
Password should have been successfully changed and hash written to the database. Able to login as the user with the newly changed password.

**Version**
Version 7.11.0
Sugar Version 6.5.25 (Build 344)

- Output of `docker version`:

```
Docker version 18.09.1, build 4c52b90
```

- Output of `docker info`:

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.604GiB
Name: redrohn.org
ID: UNFF:E3EB:4JGB:44TK:AW67:SKEI:DH7W:A2QW:MNFU:XDRL:AYR7:AJDY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This occurs on my Ubuntu 18.04 VPS hosed by OVH as well as on another Ubuntu 18.04 VPS hosted by 1and1. This same exact problem occurs even when following the guide to add persistence.

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue, but it seems to me it has to do with the following message

![image](https://user-images.githubusercontent.com/1133777/51521312-8c1fde00-1e26-11e9-882b-69b0c85fc9ee.png)

It looks like you need to configure the SMTP settings first. Did you configure them?

**Comment by kaptainkommie** [comment]
@javsalgar I'm sorry, I forgot to mention that I did configure SMTP and was able to verify SuiteCRM was able to send email. This did not resolve the issue however.

**Comment by kaptainkommie** [comment]
Related issue: https://github.com/salesagility/SuiteCRM/pull/6779

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. As soon as they publish a new version we will start the release process.
